# Generated by Django 3.2.13 on 2022-06-08 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Diagnostico",
            fields=[
                ("diagnostico", models.CharField(max_length=255)),
                (
                    "id",
                    models.IntegerField(
                        db_column="Id", primary_key=True, serialize=False
                    ),
                ),
            ],
            options={
                "db_table": "tn_diagnostico",
                "abstract": False,
                "managed": False,
            },
        ),
    ]
