# Generated by Django 3.2.13 on 2022-06-08 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_migration", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Localizacion",
            fields=[
                ("localizacion", models.CharField(max_length=255)),
                ("id", models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "tn_localizacion",
                "abstract": False,
                "managed": False,
            },
        ),
    ]
