# Generated by Django 3.2.13 on 2022-06-08 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_migration", "0003_doctor_grupo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Medico",
            fields=[
                ("nombre", models.CharField(max_length=255)),
                (
                    "id",
                    models.CharField(
                        db_column="regprof",
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
            options={
                "db_table": "tn_medicos",
                "abstract": False,
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="Doctor",
        ),
    ]
