# Generated by Django 3.2.13 on 2022-06-10 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_migration", "0005_municipio_provincia"),
    ]

    operations = [
        migrations.CreateModel(
            name="Paciente",
            fields=[
                (
                    "ci",
                    models.CharField(
                        db_column="CI",
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "apellido1",
                    models.CharField(
                        blank=True, db_column="apellido1", max_length=255, null=True
                    ),
                ),
                (
                    "apellido2",
                    models.CharField(
                        blank=True, db_column="apellido2", max_length=255, null=True
                    ),
                ),
                (
                    "nombres",
                    models.CharField(
                        blank=True, db_column="nombres", max_length=255, null=True
                    ),
                ),
                ("edad", models.IntegerField(blank=True, db_column="edad", null=True)),
                (
                    "sexo",
                    models.CharField(
                        blank=True, db_column="sexo", max_length=255, null=True
                    ),
                ),
                (
                    "piel",
                    models.CharField(
                        blank=True, db_column="piel", max_length=255, null=True
                    ),
                ),
                (
                    "calle",
                    models.CharField(
                        blank=True, db_column="calle", max_length=255, null=True
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        blank=True, db_column="numero", max_length=255, null=True
                    ),
                ),
                (
                    "edificio",
                    models.CharField(
                        blank=True, db_column="edificio", max_length=255, null=True
                    ),
                ),
                (
                    "apartamento",
                    models.IntegerField(blank=True, db_column="apartamento", null=True),
                ),
                (
                    "entre",
                    models.CharField(
                        blank=True, db_column="entre", max_length=255, null=True
                    ),
                ),
                (
                    "localidad",
                    models.CharField(
                        blank=True, db_column="localidad", max_length=255, null=True
                    ),
                ),
                (
                    "embarazada",
                    models.IntegerField(blank=True, db_column="embarazada", null=True),
                ),
                (
                    "trimestre",
                    models.CharField(
                        blank=True, db_column="trimestre", max_length=255, null=True
                    ),
                ),
                ("vih", models.IntegerField(blank=True, db_column="vih+", null=True)),
                (
                    "hc",
                    models.CharField(
                        blank=True, db_column="hc", max_length=255, null=True
                    ),
                ),
            ],
            options={
                "db_table": "t1_datosgeneralespaciente",
                "abstract": False,
                "managed": False,
            },
        ),
    ]
