# Generated by Django 3.2.13 on 2022-06-16 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_migration", "0006_paciente"),
    ]

    operations = [
        migrations.CreateModel(
            name="DatosTumor",
            fields=[
                (
                    "fechainicio",
                    models.DateField(blank=True, db_column="fechainicio", null=True),
                ),
                (
                    "idtumor",
                    models.IntegerField(
                        db_column="idtumor", primary_key=True, serialize=False
                    ),
                ),
                (
                    "fechadiagnostico",
                    models.DateField(
                        blank=True, db_column="fechadiagnostico", null=True
                    ),
                ),
                (
                    "lateralidad",
                    models.CharField(
                        blank=True, db_column="bilateral", max_length=255, null=True
                    ),
                ),
                (
                    "t",
                    models.CharField(
                        blank=True, db_column="T", max_length=255, null=True
                    ),
                ),
                (
                    "n",
                    models.CharField(
                        blank=True, db_column="N", max_length=255, null=True
                    ),
                ),
                (
                    "m",
                    models.CharField(
                        blank=True, db_column="M", max_length=255, null=True
                    ),
                ),
                (
                    "clinicopatolog",
                    models.CharField(
                        blank=True,
                        db_column="clinicopatolog",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("psa", models.FloatField(blank=True, db_column="psa", null=True)),
                (
                    "tumorprimario",
                    models.CharField(
                        blank=True, db_column="tumorprimario", max_length=255, null=True
                    ),
                ),
                (
                    "basediagnostico",
                    models.CharField(
                        blank=True,
                        db_column="basediagnostico",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "extension",
                    models.CharField(
                        blank=True, db_column="extension", max_length=255, null=True
                    ),
                ),
                (
                    "etapa",
                    models.CharField(
                        blank=True, db_column="etapa", max_length=255, null=True
                    ),
                ),
                (
                    "grado",
                    models.CharField(
                        blank=True, db_column="grado", max_length=255, null=True
                    ),
                ),
                (
                    "transf_hemat",
                    models.IntegerField(
                        blank=True, db_column="transf_hemat", null=True
                    ),
                ),
                (
                    "fechaprsintomas",
                    models.DateField(
                        blank=True, db_column="fechaprsintomas", null=True
                    ),
                ),
                (
                    "aguda",
                    models.CharField(
                        blank=True, db_column="aguda", max_length=255, null=True
                    ),
                ),
                (
                    "cronica",
                    models.CharField(
                        blank=True, db_column="cronica", max_length=255, null=True
                    ),
                ),
                (
                    "mieloide",
                    models.CharField(
                        blank=True, db_column="mieloide", max_length=255, null=True
                    ),
                ),
                (
                    "mieloma",
                    models.CharField(
                        blank=True, db_column="mieloma", max_length=255, null=True
                    ),
                ),
                (
                    "mieloidecronica",
                    models.CharField(
                        blank=True,
                        db_column="mieloidecronica",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "fuente",
                    models.CharField(
                        blank=True, db_column="fuente", max_length=255, null=True
                    ),
                ),
                (
                    "fechareporte",
                    models.DateField(blank=True, db_column="fechareporte", null=True),
                ),
            ],
            options={
                "db_table": "t1_datosgeneralestumor",
                "abstract": False,
                "managed": False,
            },
        ),
    ]
