# Generated by Django 3.2.13 on 2022-07-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_migration", "0007_datostumor"),
    ]

    operations = [
        migrations.CreateModel(
            name="Esquema",
            fields=[
                ("esquema", models.CharField(max_length=255)),
                ("id_esquema", models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "tn_esquema",
                "abstract": False,
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Medicamentos",
            fields=[
                ("tipo", models.CharField(max_length=255)),
                ("nombre", models.CharField(max_length=255)),
                ("presentacion", models.CharField(max_length=255)),
                ("cantidad", models.FloatField()),
                ("unidad", models.CharField(max_length=255)),
                (
                    "id_medicamento",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
            ],
            options={
                "db_table": "tn_medicamentos",
                "abstract": False,
                "managed": False,
            },
        ),
    ]
