# Generated by Django 3.2.13 on 2022-06-12 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("geographic_location", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="municipality",
            options={
                "default_permissions": (),
                "ordering": ["pk"],
                "verbose_name": "Municipio",
                "verbose_name_plural": "Municipios",
            },
        ),
        migrations.AlterModelOptions(
            name="province",
            options={
                "default_permissions": (),
                "ordering": ["pk"],
                "verbose_name": "Provincia",
                "verbose_name_plural": "Provincias",
            },
        ),
    ]
