# Generated by Django 4.1.7 on 2023-03-31 03:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("geographic_location", "0002_auto_20220612_0006"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="municipality",
            options={
                "ordering": ["pk"],
                "verbose_name": "Municipio",
                "verbose_name_plural": "Municipios",
            },
        ),
        migrations.AlterModelOptions(
            name="province",
            options={
                "ordering": ["pk"],
                "verbose_name": "Provincia",
                "verbose_name_plural": "Provincias",
            },
        ),
    ]
