# Generated by Django 3.2.13 on 2022-06-12 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("classifiers", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="morphology",
            options={
                "default_permissions": (),
                "ordering": ["pk"],
                "verbose_name": "Morfología",
                "verbose_name_plural": "Morfologías",
            },
        ),
        migrations.AlterModelOptions(
            name="radioisotope",
            options={
                "default_permissions": (),
                "ordering": ["pk"],
                "verbose_name": "Radio isótopo",
                "verbose_name_plural": "Radio isótopo",
            },
        ),
        migrations.AlterModelOptions(
            name="study",
            options={
                "default_permissions": (),
                "ordering": ["pk"],
                "verbose_name": "Estudio",
                "verbose_name_plural": "Estudios",
            },
        ),
        migrations.AlterModelOptions(
            name="topography",
            options={
                "default_permissions": (),
                "ordering": ["pk"],
                "verbose_name": "Topografía",
                "verbose_name_plural": "Topografías",
            },
        ),
    ]
