# Generated by Django 3.2.13 on 2022-05-22 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classifiers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RadioIsotope",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
            ],
            options={
                "verbose_name": "Radio isótopo",
                "verbose_name_plural": "Radio isótopo",
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="Study",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
            ],
            options={
                "verbose_name": "Estudio",
                "verbose_name_plural": "Estudios",
                "ordering": ["pk"],
            },
        ),
    ]
