# Generated by Django 4.1.7 on 2023-03-31 03:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("classifiers", "0002_auto_20220612_0006"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="morphology",
            options={
                "ordering": ["pk"],
                "verbose_name": "Morfología",
                "verbose_name_plural": "Morfologías",
            },
        ),
        migrations.AlterModelOptions(
            name="radioisotope",
            options={
                "ordering": ["pk"],
                "verbose_name": "Radio isótopo",
                "verbose_name_plural": "Radio isótopo",
            },
        ),
        migrations.AlterModelOptions(
            name="study",
            options={
                "ordering": ["pk"],
                "verbose_name": "Estudio",
                "verbose_name_plural": "Estudios",
            },
        ),
        migrations.AlterModelOptions(
            name="topography",
            options={
                "ordering": ["pk"],
                "verbose_name": "Topografía",
                "verbose_name_plural": "Topografías",
            },
        ),
    ]
