# Generated by Django 3.2.16 on 2023-02-24 19:39

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("patient", "0005_alter_patient_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="InternalRadiationTreatment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "treat_number",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="Numero de Tratamiento",
                    ),
                ),
                (
                    "dosis",
                    models.FloatField(blank=True, null=True, verbose_name="Dosis"),
                ),
                (
                    "time_table",
                    models.DateField(blank=True, null=True, verbose_name="Fecha"),
                ),
                (
                    "target_volume",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Volumen Diana"
                    ),
                ),
                (
                    "radiation_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Tiempo de Radioacion"
                    ),
                ),
                (
                    "fractionation",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Fraccionamiento"
                    ),
                ),
                (
                    "target_precision",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Precision al Objetivo"
                    ),
                ),
                (
                    "dosis_distribution",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Distribucion de Dosis"
                    ),
                ),
                (
                    "radioisotope",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="Radioisotopos",
                    ),
                ),
                (
                    "tests",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            (
                                "Implates con indices de dosis bajas",
                                "Implates con indices de dosis bajas",
                            ),
                            (
                                "Implates con indices de dosis altas",
                                "Implates con indices de dosis bajas",
                            ),
                            ("Implantes permanentes", "Implantes permanentes"),
                        ],
                        max_length=250,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patient.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tratamiento Radiacion Interna",
                "verbose_name_plural": "Tratamiento Radiacion Interna",
                "ordering": ["created_at"],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="InternalRadiationReg",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "treat_number",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="Numero de Tratamiento",
                    ),
                ),
                (
                    "dosis",
                    models.FloatField(blank=True, null=True, verbose_name="Dosis"),
                ),
                (
                    "time_table",
                    models.DateField(blank=True, null=True, verbose_name="Fecha"),
                ),
                (
                    "target_volume",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Volumen Diana"
                    ),
                ),
                (
                    "radiation_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Tiempo de Radioacion"
                    ),
                ),
                (
                    "fractionation",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Fraccionamiento"
                    ),
                ),
                (
                    "target_precision",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Precision al Objetivo"
                    ),
                ),
                (
                    "dosis_distribution",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Distribucion de Dosis"
                    ),
                ),
                (
                    "session_number",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Numero de Sesión"
                    ),
                ),
                (
                    "radioisotope",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="Radioisotopos",
                    ),
                ),
                (
                    "tests",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            (
                                "Implates con indices de dosis bajas",
                                "Implates con indices de dosis bajas",
                            ),
                            (
                                "Implates con indices de dosis altas",
                                "Implates con indices de dosis bajas",
                            ),
                            ("Implantes permanentes", "Implantes permanentes"),
                        ],
                        max_length=250,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patient.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro Radiacion Interna",
                "verbose_name_plural": "Registros Radiacion Interna",
                "ordering": ["created_at"],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="ExternalBeamTreat",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "treat_number",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="Numero de Tratamiento",
                    ),
                ),
                (
                    "dosis",
                    models.FloatField(blank=True, null=True, verbose_name="Dosis"),
                ),
                (
                    "time_table",
                    models.DateField(blank=True, null=True, verbose_name="Fecha"),
                ),
                (
                    "target_volume",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Volumen Diana"
                    ),
                ),
                (
                    "radiation_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Tiempo de Radioacion"
                    ),
                ),
                (
                    "fractionation",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Fraccionamiento"
                    ),
                ),
                (
                    "target_precision",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Precision al Objetivo"
                    ),
                ),
                (
                    "dosis_distribution",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Distribucion de Dosis"
                    ),
                ),
                (
                    "external_beam_config",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Configuracion del Haz Externo",
                    ),
                ),
                (
                    "tests",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            (
                                "Radioterapia de conformacion tridimensional",
                                "Radioterapia de conformacion tridimensional",
                            ),
                            (
                                "Radioterapia de intensidad modulada",
                                "Radioterapia de intensidad modulada",
                            ),
                            (
                                "Radioterapia guiada por imagenes",
                                "Radioterapia guiada por imagenes",
                            ),
                            ("Tomoterapia", "Tomoterapia"),
                            (
                                "Radiocirugia estereotactica",
                                "Radiocirugia estereotactica",
                            ),
                            (
                                "Radioterapia estereotactica corporal",
                                "Radioterapia estereotactica corporal",
                            ),
                        ],
                        max_length=250,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patient.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tratamiento Radiacion Haz Externo",
                "verbose_name_plural": "Tratamientos Radiacion Haz Externo",
                "ordering": ["created_at"],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="ExternalBeamReg",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "treat_number",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="Numero de Tratamiento",
                    ),
                ),
                (
                    "dosis",
                    models.FloatField(blank=True, null=True, verbose_name="Dosis"),
                ),
                (
                    "time_table",
                    models.DateField(blank=True, null=True, verbose_name="Fecha"),
                ),
                (
                    "target_volume",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Volumen Diana"
                    ),
                ),
                (
                    "radiation_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Tiempo de Radioacion"
                    ),
                ),
                (
                    "fractionation",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Fraccionamiento"
                    ),
                ),
                (
                    "target_precision",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Precision al Objetivo"
                    ),
                ),
                (
                    "dosis_distribution",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Distribucion de Dosis"
                    ),
                ),
                (
                    "session_number",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Numero de Sesión"
                    ),
                ),
                (
                    "external_beam_config",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Configuracion del Haz Externo",
                    ),
                ),
                (
                    "tests",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            (
                                "Radioterapia de conformacion tridimensional",
                                "Radioterapia de conformacion tridimensional",
                            ),
                            (
                                "Radioterapia de intensidad modulada",
                                "Radioterapia de intensidad modulada",
                            ),
                            (
                                "Radioterapia guiada por imagenes",
                                "Radioterapia guiada por imagenes",
                            ),
                            ("Tomoterapia", "Tomoterapia"),
                            (
                                "Radiocirugia estereotactica",
                                "Radiocirugia estereotactica",
                            ),
                            (
                                "Radioterapia estereotactica corporal",
                                "Radioterapia estereotactica corporal",
                            ),
                        ],
                        max_length=250,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patient.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro Radiacion Haz Externo",
                "verbose_name_plural": "Registros Radiacion Haz Externo",
                "ordering": ["created_at"],
                "default_permissions": (),
            },
        ),
    ]
