# Generated by Django 4.2.1 on 2023-06-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pathologic_anathomy", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="biopsyrequest",
            name="address",
        ),
        migrations.RemoveField(
            model_name="biopsyrequest",
            name="age",
        ),
        migrations.RemoveField(
            model_name="biopsyrequest",
            name="especiality",
        ),
        migrations.RemoveField(
            model_name="biopsyrequest",
            name="race",
        ),
        migrations.RemoveField(
            model_name="biopsyrequest",
            name="sex",
        ),
        migrations.AddField(
            model_name="biopsyrequest",
            name="especialty",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Especialidad"
            ),
        ),
        migrations.AlterField(
            model_name="biopsyrequest",
            name="biopsy_id",
            field=models.CharField(
                editable=False, max_length=100, null=True, verbose_name="No Biopsia"
            ),
        ),
        migrations.AlterField(
            model_name="biopsyrequest",
            name="biopsy_type",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Biopsia de Mama"),
                    (2, "Biopsia de Cuello"),
                    (3, "Siopsia Digestivo"),
                    (4, "Biopsia de Linfoma"),
                    (5, "Biopsia de Ginecologia"),
                    (6, "Biopsia de Cabeza"),
                ],
                null=True,
                verbose_name="Tipo de Biopsia",
            ),
        ),
        migrations.AlterField(
            model_name="biopsyrequest",
            name="health_area",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Area de Salud"
            ),
        ),
        migrations.AlterField(
            model_name="biopsyrequest",
            name="sample_biopsy",
            field=models.CharField(max_length=255, verbose_name="Tipo de Muestra"),
        ),
    ]
