# Generated by Django 4.2.1 on 2023-06-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pathologic_anathomy", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="biopsyrequest",
            name="address",
        ),
        migrations.RemoveField(
            model_name="biopsyrequest",
            name="age",
        ),
        migrations.RemoveField(
            model_name="biopsyrequest",
            name="race",
        ),
        migrations.RemoveField(
            model_name="biopsyrequest",
            name="sex",
        ),
        migrations.AlterField(
            model_name="biopsyrequest",
            name="especiality",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Especialidad"
            ),
        ),
        migrations.AlterField(
            model_name="biopsyrequest",
            name="health_area",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Area de Salud"
            ),
        ),
        migrations.AlterField(
            model_name="biopsyrequest",
            name="sample_biopsy",
            field=models.CharField(max_length=255, verbose_name="Tipo de Muestra"),
        ),
    ]
