# Generated by Django 4.2.1 on 2023-11-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathologic_anathomy', '0002_remove_biopsyrequest_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='biopsyrequest',
            name='verificated',
            field=models.BooleanField(default=False, verbose_name='Biopsia Verificada'),
        ),
    ]
