# Generated by Django 3.2.16 on 2023-11-13 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pathologic_anathomy', '0003_biopsyrequest_verificated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Head',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.CharField(max_length=255)),
                ('biopsy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='biopsy_diagnostic_head', to='pathologic_anathomy.biopsyrequest')),
            ],
        ),
    ]
