# Generated by Django 3.2.16 on 2023-11-13 19:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pathologic_anathomy", "0007_auto_20231113_1253"),
    ]

    operations = [
        migrations.AlterField(
            model_name="head",
            name="tipo_extension_parcial",
            field=models.CharField(
                blank=True,
                max_length=1000,
                null=True,
                verbose_name="Tipo de extensión parcial",
            ),
        ),
    ]
