# Generated by Django 3.2.16 on 2023-11-13 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathologic_anathomy', '0013_alter_head_num_ganglios_linfaticos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='head',
            name='num_ganglios_linfaticos',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de Ganglios linfáticos involucrados'),
        ),
    ]
