# Generated by Django 4.2.1 on 2023-11-14 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pathologic_anathomy', '0019_head_clasificacion_tumor'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeckBiopsyDiagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_muestra', models.IntegerField(choices=[(1, 'Resección Endoscópica'), (2, 'Esophagectomía'), (3, 'Esophagogastrectomía'), (4, 'otro (especifique):'), (5, 'no especificado')], verbose_name='Tipo de Muestra')),
                ('tipo_muestra_otro', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Otro tipo de muestra (especifique)')),
                ('sitio_tumor', models.IntegerField(choices=[(1, 'Esófago cervical (proximal)'), (2, 'Medio esófago, el superior esófago torácico'), (3, 'Medio esófago, el intermedio esófago torácico'), (4, 'Medio esófago, no especificado en otra forma'), (5, 'Esófago distal ( esófago torácico)'), (6, 'Unión Esophagogastrica (EGJ)'), (7, 'Estómago /cardias Proximal'), (8, 'otro (especifique):'), (9, 'El esófago, no especificado en otra forma')], verbose_name='Sitio del Tumor')),
                ('sitio_tumor_otro', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Otro sitio del tumor (especifique)')),
                ('relacion_tumor_union', models.IntegerField(choices=[(1, 'el tumor está enteramente ubicado dentro del esófago tubular y no involucra la unión esophagogastrica'), (2, 'el punto medio del tumor yace en el esófago del distal y el tumor involucra la unió esophagogastrica'), (3, 'el punto medio del tumor está localizado en la unión esophagogastrica'), (4, 'el punto medio del tumor es 2 cm o menos en el estómago  proximal o el cardias y el tumor involucra la unión esophagogastrica'), (5, 'no especificado'), (6, 'no puede ser evaluado')], verbose_name='Relación de Tumor con la unión Esophagogastric')),
                ('distancia_centro_tumor_union', models.FloatField(blank=True, null=True, verbose_name='\n            El protocolo de cáncer del estómago si ya sea: \n            (1) el tumor involucrara el EGJ, pero el punto medio es más que 2 cm del estómago proximal o \n            (2) el punto medio está menos de 2 cm del estómago proximal, pero el tumor no involucra al EGJ. \n            La distancia de centro del tumor a la unión esophagogastric (especifique, si aplicable) (los centímetros)\n        ')),
                ('tumor_max_size', models.FloatField(verbose_name='La Máxima Dimensión del Tumor (centímetros)')),
                ('tumor_size', models.FloatField(verbose_name='La Dimensión del Tumor (centímetros)')),
                ('no_puede_aplicable', models.CharField(blank=True, max_length=5000, null=True, verbose_name='No puede aplicable (explique): ')),
                ('tipo_histologia', models.IntegerField(blank=True, choices=[(1, 'Adenocarcinoma'), (2, 'Carcinoma  adenóideo quistito'), (3, 'Carcinoma Mucoepidermoide'), (4, 'Carcinoma mixto  adenoneuroendocrino'), (5, 'Carcinoma indiferenciado con componente glandular'), (6, 'Carcinoma de  célula escamoso'), (7, 'Carcinoma de la célula escamoso Basaloide'), (8, 'Carcinoma Adenoescamoso'), (9, 'Carcinoma de celulas fusiforme (escamoso)'), (10, 'Carcinoma Verrucoso (escamoso)'), (11, 'Carcinoma indiferenciado con componente escamoso'), (12, 'Carcinoma indiferenciado'), (13, 'Carcinoma  neuroendocrino de  célula grande'), (14, 'Carcinoma neuroendocrino de  célula pequeñas'), (15, 'Carcinoma Neuroendocrino (pobremente diferenciado)'), (16, 'Otro tipo  histológico que no figura en la lista (especifique):'), (17, 'Carcinoma, el tipo no puede ser determinado')], null=True, verbose_name='Tipo Histología. Nota: Seleccione esta opción sólo si el de células grande o célula pequeña no puede ser determinada')),
                ('grado_histolico', models.IntegerField(blank=True, choices=[(1, 'G1: Bien diferenciado'), (2, 'G2: Moderadamente diferenciado'), (3, 'G3: Pobremente diferenciado, no diferenciado'), (4, 'GX: No puede ser evaluado')], null=True, verbose_name='Grado Histológico (El grado grado histológico no es aplicable para el carcinoma adenoideo quistito, \n            mucoepidermoide, el bien diferenciado, el tumor neuroendocrino y el carcinoma neuroendocrino). \n            ')),
                ('tumor_extension', models.IntegerField(choices=[(1, 'Ninguna evidencia de tumor primario'), (2, 'displasia de alto grado/  carcinoma  in situ, definido como  células cancerosas confinaron al epitelio sin atravesar membrana basal'), (3, 'el tumor invade la lámina  propia'), (4, 'el tumor invade la muscularis mucosae'), (5, 'el tumor invade la submucosa'), (6, 'el tumor invade la muscular propia'), (7, 'el tumor invade la adventicia'), (8, 'el tumor invade  estructuras/órgano # adyacentes (especifique):'), (9, 'no puede ser evaluado')], verbose_name='La Extensión del Tumor. Nota: Las estructuras adyacentes del esófago incluyen la pleura, \n            el pericardio, la vena ácigos, el diafragma, el peritoneo, la aorta, cuerpo vertebral, y la vía aérea')),
                ('todos_los_margenes_involucrados', models.BooleanField(default=False, verbose_name=' todos los márgenes son involucrados por carcinoma invasivo,\n            displasia, y metaplasia intestinal')),
                ('margenes_examinados', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Los márgenes examinados. Nota: Los márgenes pueden incluir a proximal, distal, radial,\n            mucosal, en profundidad, y otros.')),
                ('distancia_carcinoma_invasivo_margen_cercano_cm', models.FloatField(blank=True, null=True, verbose_name='La distancia del carcinoma invasivo al margen más cercano\n                (centímetros)')),
                ('distancia_carcinoma_invasivo_margen_cercano_mm', models.FloatField(blank=True, null=True, verbose_name='La distancia del carcinoma invasivo al margen más cercano\n                (milímetros)')),
                ('margen_proximal', models.IntegerField(blank=True, choices=[(1, 'no puede ser evaluado'), (2, 'involucrado por carcinoma invasivo'), (3, 'no involucrado por carcinoma invasivo'), (4, 'involucrado por displasia'), (5, 'involucrado por displasia escamosa de bajo grado'), (6, 'involucrado por displasia escamosa de alto grado'), (7, 'involucrado por displasia glandular de bajo grado'), (8, 'involucrado por displasia glandular de alto grado'), (9, 'involucrado por metaplasia intestinal (el esófago Barrett) sin displasia')], null=True, verbose_name='Margen Proximal')),
                ('margen_distal', models.IntegerField(blank=True, choices=[(1, 'no puede ser evaluado'), (2, 'involucrado por carcinoma invasivo'), (3, 'no involucrado por carcinoma invasivo'), (4, 'involucrado por displasia'), (5, 'involucrado por displasia escamosa de bajo grado'), (6, 'involucrado por displasia escamosa de alto grado'), (7, 'involucrado por displasia glandular de bajo grado'), (8, 'involucrado por displasia glandular de alto grado'), (9, 'involucrado por metaplasia intestinal (el esófago Barrett) sin displasia')], null=True, verbose_name='Margen Distal')),
                ('margen_radial', models.IntegerField(blank=True, choices=[(1, 'no puede ser evaluado'), (2, 'no involucrado por carcinoma invasivo'), (3, 'involucrado por carcinoma invasivo')], null=True, verbose_name='Margen Radial')),
                ('otros_margenes_sophagectomia_y_esophagogastrectomia', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Otro Margen(s) (requerido único si es aplicable). Especifique')),
                ('otros_margenes_sophagectomia_y_esophagogastrectomia_especificaciones', models.IntegerField(blank=True, choices=[(1, 'no puede ser evaluado'), (2, 'no involucrado por carcinoma invasivo'), (3, 'involucrado por carcinoma invasivo')], null=True, verbose_name='Otro Margen(s)')),
                ('margen_mucosal', models.IntegerField(blank=True, choices=[(1, 'no puede ser evaluado'), (2, 'involucrado por carcinoma invasivo'), (3, 'no involucrado por carcinoma invasivo'), (4, 'involucrado por displasia'), (5, 'involucrado por displasia escamoso de bajo grado'), (6, 'involucrado por displasia escamoso de alto grado'), (7, 'involucrado por displasia glandular de bajo grado'), (8, 'involucrado por displasia glandular de alto grado'), (9, 'involucrado por metaplasia intestinal (el esófago Barrett) sin displasia')], null=True, verbose_name='Margen Mucosal')),
                ('margen_profundo', models.IntegerField(blank=True, choices=[(1, 'no puede ser evaluado'), (2, 'No involucrado por carcinoma invasivo'), (3, 'involucrado por carcinoma invasivo')], null=True, verbose_name='Margen Profundo')),
                ('otros_margenes_reseccion_endoscopica', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Otro Margen(s) (requerido único si es aplicable). Especifique')),
                ('otros_margenes_reseccion_endoscopica_especificaciones', models.IntegerField(blank=True, choices=[(1, 'no puede ser evaluado'), (2, 'no involucrado por carcinoma invasivo'), (3, 'involucrado por carcinoma invasivo')], null=True, verbose_name='Otro Margen(s)')),
                ('invasion_linfovascular', models.IntegerField(choices=[(1, 'No identificado'), (2, 'presente'), (3, 'no puede estar resuelto')], verbose_name='Invasión Linfovascular')),
                ('invasion_perineural', models.IntegerField(choices=[(1, 'No identificado'), (2, 'presente'), (3, 'no puede estar resuelto')], verbose_name='Invasión Perineural')),
                ('ganglios_linfaticos_encontrados', models.BooleanField(default=False, verbose_name='Ganglios Linfáticos Encontrados')),
                ('num_ganglios_linfaticos', models.IntegerField(blank=True, null=True, verbose_name='Número de gânglios linfáticos Involucrados')),
                ('num_ganglios_no_determinado', models.CharField(blank=True, max_length=5000, null=True, verbose_name='El número de ganglios no puede ser determinado (explique)')),
                ('clasificacion_tumor', models.IntegerField(choices=[(1, 'PT'), (2, 'N'), (3, 'M')], verbose_name='Clasificación Tumor')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('biopsy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pathologic_anathomy.biopsyrequest')),
            ],
            options={
                'verbose_name': 'Diagnóstico Biopcia de Cuello(Esófago)',
                'verbose_name_plural': 'Diagnósticos Biopcias de Cuello(Esófago)',
                'ordering': ['id'],
            },
        ),
    ]
