# Generated by Django 4.2.1 on 2023-11-14 18:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "pathologic_anathomy",
            "0021_rename_otros_margenes_reseccion_endoscopica_neckbiopsydiagnostic_otros_margenes_ee_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="neckbiopsydiagnostic",
            name="clasificacion_tumor",
            field=models.IntegerField(
                choices=[(1, "PT"), (2, "N"), (3, "M")],
                default=None,
                verbose_name="Clasificación Tumor",
            ),
        ),
    ]
