# Generated by Django 4.2.1 on 2023-11-15 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pathologic_anathomy", "0032_head_clasificacion_tumor"),
    ]

    operations = [
        migrations.AddField(
            model_name="neckbiopsydiagnostic",
            name="margen_mas_cercano",
            field=models.CharField(
                blank=True,
                max_length=5000,
                null=True,
                verbose_name="Especifique el margen más cercano:",
            ),
        ),
        migrations.AlterField(
            model_name="head",
            name="indice_mitosis",
            field=models.FloatField(
                default=0,
                verbose_name="Índice de mitosis por 2 mm2:\n        Nota: La Mitosis debería ser contada en 10 campos de alto poder consecutivos (HPF) a 400x en el área más activa de mitosis.\n        Para la mayoría de los microscopios, 10 (HPF) es aproximadamente equivalente a 2.5 mm2",
            ),
        ),
        migrations.AlterField(
            model_name="neckbiopsydiagnostic",
            name="distancia_centro_tumor_union",
            field=models.FloatField(
                blank=True,
                null=True,
                verbose_name="\n            El protocolo de cáncer del estómago si ya sea:\n            (1) el tumor involucrara el EGJ, pero el punto medio es más que 2 cm del estómago proximal o\n            (2) el punto medio está menos de 2 cm del estómago proximal, pero el tumor no involucra al EGJ.\n            La distancia de centro del tumor a la unión esophagogastric (especifique, si aplicable) (los centímetros)\n        ",
            ),
        ),
        migrations.AlterField(
            model_name="neckbiopsydiagnostic",
            name="grado_histolico",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "G1: Bien diferenciado"),
                    (2, "G2: Moderadamente diferenciado"),
                    (3, "G3: Pobremente diferenciado, no diferenciado"),
                    (4, "GX: No puede ser evaluado"),
                ],
                null=True,
                verbose_name="Grado Histológico (El grado grado histológico no es aplicable para el carcinoma adenoideo quistito,\n            mucoepidermoide, el bien diferenciado, el tumor neuroendocrino y el carcinoma neuroendocrino).\n            ",
            ),
        ),
        migrations.AlterField(
            model_name="neckbiopsydiagnostic",
            name="tumor_extension",
            field=models.IntegerField(
                choices=[
                    (1, "Ninguna evidencia de tumor primario"),
                    (
                        2,
                        "displasia de alto grado/  carcinoma  in situ, definido como  células cancerosas confinaron al epitelio sin atravesar membrana basal",
                    ),
                    (3, "el tumor invade la lámina  propia"),
                    (4, "el tumor invade la muscularis mucosae"),
                    (5, "el tumor invade la submucosa"),
                    (6, "el tumor invade la muscular propia"),
                    (7, "el tumor invade la adventicia"),
                    (
                        8,
                        "el tumor invade  estructuras/órgano # adyacentes (especifique):",
                    ),
                    (9, "no puede ser evaluado"),
                ],
                verbose_name="La Extensión del Tumor. Nota: Las estructuras adyacentes del esófago incluyen la pleura,\n            el pericardio, la vena ácigos, el diafragma, el peritoneo, la aorta, cuerpo vertebral, y la vía aérea",
            ),
        ),
    ]
