# Generated by Django 4.2.1 on 2023-11-15 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "pathologic_anathomy",
            "0033_neckbiopsydiagnostic_margen_mas_cercano_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="StomacBiopsyDiagnostic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_muestra",
                    models.IntegerField(
                        choices=[
                            (1, "resección Endoscopic"),
                            (2, "gastrectomia parcial, proximal"),
                            (3, "gastrectomia parcial, distal"),
                            (4, "gastrectomía parcial, otro (especifique)"),
                            (5, "gastrectomía total"),
                            (6, "otro (especifique)"),
                            (7, "no especificado"),
                        ],
                        verbose_name="Tipo de Muestra",
                    ),
                ),
                (
                    "tipo_muestra_otro",
                    models.CharField(
                        blank=True,
                        max_length=5000,
                        null=True,
                        verbose_name="Otro tipo de muestra (especifique)",
                    ),
                ),
                (
                    "sitio_tumor",
                    models.IntegerField(
                        choices=[
                            (1, "cardias"),
                            (2, "fundus(pared anterior)"),
                            (3, "fundus(pared posterior)"),
                            (4, "cuerpo(pared anterior)"),
                            (5, "cuerpo(pared posterior)"),
                            (6, "cuerpo(curvatura menor)"),
                            (7, "cuerpo(curvatura mayor)"),
                            (8, "antro(pared anterior)"),
                            (9, "antro(pared posterior)"),
                            (10, "antro(curvatura menor)"),
                            (11, "antro(curvatura mayor)"),
                            (12, "píloro"),
                            (13, "otro (especifique)"),
                            (14, "no especificado"),
                        ],
                        verbose_name="Sitio del Tumor",
                    ),
                ),
                (
                    "sitio_tumor_otro",
                    models.CharField(
                        blank=True,
                        max_length=5000,
                        null=True,
                        verbose_name="Otro sitio del tumor (especifique)",
                    ),
                ),
                (
                    "tumor_max_size",
                    models.FloatField(
                        verbose_name="La Máxima Dimensión del Tumor (centímetros)"
                    ),
                ),
                (
                    "tumor_size",
                    models.FloatField(
                        verbose_name="La Dimensión del Tumor (centímetros)"
                    ),
                ),
                (
                    "no_puede_aplicable",
                    models.CharField(
                        blank=True,
                        max_length=5000,
                        null=True,
                        verbose_name="No puede aplicable (explique): ",
                    ),
                ),
                (
                    "tipo_histologico",
                    models.IntegerField(
                        choices=[
                            (1, "adenocarcinoma tipo intestinal"),
                            (
                                2,
                                "adenocarcinoma tipo difuso(incluye carcinoma en anillo de sello, clasificado como > 50%) celulas en anillo de sello",
                            ),
                            (
                                3,
                                "adenocarcinoma tipo mixto (aproximadamente igual cantidades de intestinal y difuso)",
                            ),
                            (
                                4,
                                "adenocarcinoma tubular (intestinal) carcinoma (incluyendo carcinoma de célula en anillo de sello y otras variantes)",
                            ),
                            (5, "adenocarcinoma mucinoso ( > 50% de musina)"),
                            (6, "adenocarcinoma papilar"),
                            (
                                7,
                                "carcinoma mixto ( mezcla de glandular (/ papillary tubular) y células en anillo de sello",
                            ),
                            (8, "adenocarcinoma Hepatoide"),
                            (
                                9,
                                "carcinoma con estroma linfoide (el carcinoma medular)",
                            ),
                            (10, "carcinoma neuroendocrino de célula grande"),
                            (11, "carcinoma neuroendocrino de células pequeñas"),
                            (12, "carcinoma Neuroendocrino (pobremente diferenciado)"),
                            (13, "carcinoma mixto adenoneuroendocrine"),
                            (14, "carcinoma de célula escamosa"),
                            (15, "carcinoma Adenoescamoso"),
                            (16, "el carcinoma indiferenciado"),
                            (
                                17,
                                "otro tipo del histologico que no figura en la lista (especifique)",
                            ),
                        ],
                        verbose_name="El Tipo Histológico",
                    ),
                ),
                (
                    "tipo_histologico_otro",
                    models.CharField(
                        blank=True,
                        max_length=5000,
                        null=True,
                        verbose_name="Otro Tipo Histológico (especifique)",
                    ),
                ),
                (
                    "grado_histologico",
                    models.IntegerField(
                        choices=[
                            (1, "El bien diferenciado"),
                            (2, "Moderadamente diferenciado"),
                            (3, "Pobremente diferenciado, no diferenciado"),
                            (4, "otro (especifique)"),
                            (5, "No puede ser evaluado"),
                            (6, "no se aplica"),
                        ],
                        verbose_name="El Grado del Histológico",
                    ),
                ),
                (
                    "grado_histologico_otro",
                    models.CharField(
                        blank=True,
                        max_length=5000,
                        null=True,
                        verbose_name="Otro Tipo Histológico (especifique)",
                    ),
                ),
                (
                    "extension_tumor",
                    models.IntegerField(
                        choices=[
                            (1, "ninguna prueba de tumor primario"),
                            (
                                2,
                                "carcinoma in situ: tumor intraepithelial sin invasión de la lámina propia, displasia severa",
                            ),
                            (3, "tumor invade la lámina propia"),
                            (4, "el tumor invade la muscularis mucosae"),
                            (5, "el tumor invade la submucosa"),
                            (6, "el tumor invade la muscular propia"),
                            (
                                7,
                                "el tumor penetra en el tejido conjuntivo subseroso sin invasión del peritoneo visceral o estructuras adyacentes",
                            ),
                            (8, "el tumor invade la serosa (el peritoneo visceral)"),
                            (
                                9,
                                "el tumor invade a estructures/órganos adyacentes (especifique)",
                            ),
                            (10, "no puede ser evaluado"),
                        ],
                        verbose_name="Extensión del Tumor",
                    ),
                ),
                (
                    "estructuras_adyacentes_invadidas",
                    models.CharField(
                        blank=True,
                        max_length=5000,
                        null=True,
                        verbose_name="El tumor invade a estructuras/órganos adyacentes(especifique). Las estructuras adyacentes del estómago incluyen el bazo, el colon\n            transverso, el hígado, el diafragma, el páncreas, la pared abdominal, la glándula suprarrenal, renale intestino delgado, y el retroperitoneo. \n            La extensión intramural del duodeno o el esófago no es considerado invasión de una estructura adyacente, pero está clasificado usa la profundidad de la máxima invasión en cualquier\n            de estos sitios.",
                    ),
                ),
                (
                    "todos_los_margenes_involucrados",
                    models.BooleanField(
                        default=False,
                        verbose_name=" Todos los márgenes son involucrados por carcinoma invasor y displasia",
                    ),
                ),
                (
                    "margenes_examinados",
                    models.CharField(
                        blank=True,
                        max_length=5000,
                        null=True,
                        verbose_name="Los márgenes examinados. Nota: Los márgenes pueden incluir a proximal, distal, omental(radial), mucosal, profundidad y otros.",
                    ),
                ),
                (
                    "distancia_carcinoma_invasivo_margen_cercano_cm",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="La distancia del carcinoma invasivo al margen más cercano\n                (centímetros)",
                    ),
                ),
                (
                    "distancia_carcinoma_invasivo_margen_cercano_mm",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="La distancia del carcinoma invasivo al margen más cercano\n                (milímetros)",
                    ),
                ),
                (
                    "margen_mas_cercano",
                    models.CharField(
                        blank=True,
                        max_length=5000,
                        null=True,
                        verbose_name="Especifique el margen más cercano:",
                    ),
                ),
                (
                    "margen_proximal",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "no puede ser evaluado"),
                            (2, "Involucrado por carcinoma invasivo"),
                            (3, "no involucrado por carcinoma invasivo"),
                            (4, "no involucrado por displasia"),
                            (
                                5,
                                "no involucrado por carcinoma in situ (displasia de alto grado)",
                            ),
                            (6, "no involucrado por displasia de bajo grado"),
                        ],
                        null=True,
                        verbose_name="Margen Proximal(Solo para especímenes de gastrectomía)",
                    ),
                ),
                (
                    "margen_distal",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "no puede ser evaluado"),
                            (2, "Involucrado por carcinoma invasivo"),
                            (3, "no involucrado por carcinoma invasivo"),
                            (4, "no involucrado por displasia"),
                            (
                                5,
                                "no involucrado por carcinoma in situ (displasia de alto grado)",
                            ),
                            (6, "no involucrado por displasia de bajo grado"),
                        ],
                        null=True,
                        verbose_name="Margen Distal(Solo para especímenes de gastrectomía)",
                    ),
                ),
                (
                    "margen_radial",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "no puede ser evaluado"),
                            (2, "involucrado por carcinoma invasivo"),
                            (3, "no involucrado por carcinoma invasivo"),
                        ],
                        null=True,
                        verbose_name="Márgenes Omental(Radial)",
                    ),
                ),
                (
                    "mayor_margen_omental",
                    models.FloatField(
                        verbose_name="El + que el Mayor margen del omental involucró por carcinoma del invasive"
                    ),
                ),
                (
                    "inferior_margen_omental",
                    models.FloatField(
                        verbose_name="El + que el margen Inferior del omental involucró por carcinoma del invasive"
                    ),
                ),
                (
                    "otros_margenes_gastrectomia",
                    models.CharField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="Otro Margen(s) (requerido único si aplicable). Especifique",
                    ),
                ),
                (
                    "otros_margenes_gastrectomía_especificaciones",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "no puede ser evaluado"),
                            (2, "involucrado por carcinoma invasivo"),
                            (3, "no involucrado por carcinoma invasivo"),
                        ],
                        null=True,
                        verbose_name="Otro Margen(s) Clasificación",
                    ),
                ),
                (
                    "margen_mucosal",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "no puede ser evaluado"),
                            (2, "involucrado por carcinoma invasivo"),
                            (3, "no involucrado por carcinoma invasivo"),
                            (4, "no involucrado por displasia"),
                            (
                                5,
                                "involucrado por carcinoma in situ (displasia de alta calidad)",
                            ),
                            (6, "involucrado por displasia de baja calidad"),
                        ],
                        null=True,
                        verbose_name="Margen Mucosal(Para especímenes sólo de resección del endoscopic)",
                    ),
                ),
                (
                    "margen_profundo",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "no puede ser evaluado"),
                            (2, "no involucrado por carcinoma invasivo"),
                            (3, "involucrado por carcinoma invasivo"),
                        ],
                        null=True,
                        verbose_name="Margen Profundo(Para especímenes sólo de resección del endoscopic)",
                    ),
                ),
                (
                    "otros_margenes_RE",
                    models.CharField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="Otro Margen(s) (requerido único si aplicable). Especifique",
                    ),
                ),
                (
                    "otros_margenes_RE_especificaciones",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "no puede ser evaluado"),
                            (2, "involucrado por carcinoma invasivo"),
                            (3, "no involucrado por carcinoma invasivo"),
                        ],
                        null=True,
                        verbose_name="Otro Margen(s) Clasificación",
                    ),
                ),
                (
                    "invasion_linfovascular",
                    models.IntegerField(
                        choices=[
                            (1, "no identificado"),
                            (2, "presente"),
                            (3, "no puede estar resuelto"),
                        ],
                        verbose_name="Invasión Linfovascular",
                    ),
                ),
                (
                    "invasion_perineural",
                    models.IntegerField(
                        choices=[
                            (1, "No identificado"),
                            (2, "Presente"),
                            (3, "No Puede Ser determinado"),
                        ],
                        verbose_name="Invasión Perineural",
                    ),
                ),
                (
                    "ganglios_linfaticos_encontrados",
                    models.BooleanField(
                        default=False, verbose_name="Ganglios Linfáticos Encontrados"
                    ),
                ),
                (
                    "num_ganglios_linfaticos",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Número de gânglios linfáticos Involucrados",
                    ),
                ),
                (
                    "num_ganglios_no_determinado",
                    models.CharField(
                        blank=True,
                        max_length=5000,
                        null=True,
                        verbose_name="El número de ganglios no puede ser determinado (explique)",
                    ),
                ),
                (
                    "clasificacion_tumor",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "PT"), (2, "N"), (3, "M")],
                        default=None,
                        null=True,
                        verbose_name="Clasificación Tumor",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "biopsy",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pathologic_anathomy.biopsyrequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Diagnóstico Biopcia Digestivo(Estómago)",
                "verbose_name_plural": "Diagnósticos Biopcia Digestivo(Estómago)",
                "ordering": ["id"],
            },
        ),
    ]
