# Generated by Django 4.2.1 on 2023-11-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pathologic_anathomy", "0035_neckbiopsydiagnostic_tipo_histologico_otro"),
    ]

    operations = [
        migrations.AddField(
            model_name="neckbiopsydiagnostic",
            name="estructuras_adyacentes_invadidas",
            field=models.CharField(
                blank=True,
                max_length=5000,
                null=True,
                verbose_name="El tumor invade a estructuras/órganos adyacentes(especifique). Las estructuras adyacentes del estómago incluyen \n            la pleura, el pericardio, la vena ácigos, el diafragma, el peritoneo, la aorta, cuerpo vertebral y la vía aérea.",
            ),
        ),
        migrations.AlterField(
            model_name="neckbiopsydiagnostic",
            name="tumor_extension",
            field=models.IntegerField(
                choices=[
                    (1, "Ninguna evidencia de tumor primario"),
                    (
                        2,
                        "displasia de alto grado/  carcinoma  in situ, definido como  células cancerosas confinaron al epitelio sin atravesar membrana basal",
                    ),
                    (3, "el tumor invade la lámina  propia"),
                    (4, "el tumor invade la muscularis mucosae"),
                    (5, "el tumor invade la submucosa"),
                    (6, "el tumor invade la muscular propia"),
                    (7, "el tumor invade la adventicia"),
                    (
                        8,
                        "el tumor invade  estructuras/órgano # adyacentes (especifique):",
                    ),
                    (9, "no puede ser evaluado"),
                ],
                verbose_name="La Extensión del Tumor.",
            ),
        ),
    ]
