# Generated by Django 4.2.1 on 2023-11-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "pathologic_anathomy",
            "0036_neckbiopsydiagnostic_estructuras_adyacentes_invadidas_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="stomacbiopsydiagnostic",
            old_name="otros_margenes_gastrectomía_especificaciones",
            new_name="otros_margenes_gastrectomia_especificaciones",
        ),
        migrations.AlterField(
            model_name="stomacbiopsydiagnostic",
            name="margen_radial",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "no puede ser evaluado"),
                    (2, "involucrado por carcinoma invasivo"),
                    (3, "no involucrado por carcinoma invasivo"),
                ],
                null=True,
                verbose_name="Márgenes Omental(Radial)(Solo para especímenes de gastrectomía)",
            ),
        ),
    ]
