# Generated by Django 4.2.1 on 2023-11-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "pathologic_anathomy",
            "0037_rename_otros_margenes_gastrectomía_especificaciones_stomacbiopsydiagnostic_otros_margenes_gastrectom",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="stomacbiopsydiagnostic",
            name="tipo_muestra",
            field=models.IntegerField(
                choices=[
                    (1, "resección endoscopica"),
                    (2, "gastrectomia parcial, proximal"),
                    (3, "gastrectomia parcial, distal"),
                    (4, "gastrectomía parcial, otro (especifique)"),
                    (5, "gastrectomía total"),
                    (6, "otro (especifique)"),
                    (7, "no especificado"),
                ],
                verbose_name="Tipo de Muestra",
            ),
        ),
    ]
