# Generated by Django 4.2.1 on 2023-11-15 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pathologic_anathomy", "0039_alter_stomacbiopsydiagnostic_grado_histologico"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stomacbiopsydiagnostic",
            name="mayor_margen_omental",
            field=models.FloatField(
                blank=True,
                null=True,
                verbose_name="El + que el Mayor margen del omental involucró por carcinoma del invasive",
            ),
        ),
    ]
