# Generated by Django 4.2.1 on 2023-11-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathologic_anathomy', '0040_alter_stomacbiopsydiagnostic_mayor_margen_omental'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stomacbiopsydiagnostic',
            name='inferior_margen_omental',
            field=models.FloatField(blank=True, null=True, verbose_name='El + que el margen Inferior del omental involucró por carcinoma del invasive'),
        ),
    ]
