# Generated by Django 4.2.1 on 2023-11-15 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pathologic_anathomy", "0045_alter_head_niveles_ganglionares"),
    ]

    operations = [
        migrations.CreateModel(
            name="LinfomaBiopsyDiagnostic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "especimen",
                    models.CharField(
                        choices=[
                            ("el ganglio linfático(s)", "El ganglio linfático(s)"),
                            ("otro", "Otro (especifique)"),
                            (
                                "no especificado el procedimiento",
                                "No especificado el procedimiento",
                            ),
                            ("la biopsia", "La biopsia"),
                            ("la resección", "La resección"),
                            ("otro (especifique)", "Otro (especifique)"),
                            ("no especificado", "No especificado"),
                        ],
                        max_length=100,
                        verbose_name="El espécimen (seleccione todo lo que aplique)",
                    ),
                ),
                (
                    "otro_especimen",
                    models.CharField(
                        blank=True,
                        max_length=5000,
                        null=True,
                        verbose_name="Otro Espécimen (especifique)",
                    ),
                ),
                (
                    "sitio_tumor",
                    models.CharField(
                        choices=[
                            ("el ganglio linfático(s)", "El ganglio linfático(s)"),
                            ("el sitio no especificado", "El sitio no especificado"),
                        ],
                        max_length=100,
                        verbose_name="El sitio del tumor (seleccione todo lo que aplique)",
                    ),
                ),
                (
                    "sitio_tumor_especificacion",
                    models.CharField(
                        blank=True,
                        max_length=5000,
                        null=True,
                        verbose_name="Especifique sitio(s) del tumor",
                    ),
                ),
                (
                    "otro_tejido_fino_u_organo",
                    models.CharField(
                        blank=True,
                        max_length=5000,
                        null=True,
                        verbose_name="Otro tejido fino (s) u otro órgano (s) (especifique)",
                    ),
                ),
                (
                    "no_especificado",
                    models.CharField(
                        blank=True,
                        max_length=5000,
                        null=True,
                        verbose_name="No especificado",
                    ),
                ),
                (
                    "histologic_type",
                    models.IntegerField(
                        choices=[
                            (
                                1,
                                "Hodgkin Lymphoma, histologic no puede ser determinado",
                            ),
                            (
                                2,
                                "Linfoma de Hodgkin clásico, subtipo histológico no puede ser determinado",
                            ),
                            (3, "Linfoma de Hodgkin con predominio nodular"),
                            (4, "Linfoma de Hodgkin esclerosis nodular"),
                            (5, "Linfoma de Hodgkin clásico celularidad mixta"),
                            (6, "Linfoma de Hodgkin clásico rico en linfocitos"),
                            (7, "Linfoma de Hodgkin con depleción linfocítica"),
                        ],
                        verbose_name="HistologicType (basada en la clasificación de 2008 quienes)",
                    ),
                ),
                (
                    "pathologic_tumor_extensions",
                    models.CharField(
                        choices=[
                            ("Afecta la médula ósea", "Afecta la médula ósea"),
                            (
                                "Afecta el sitio específico",
                                "Afecta el sitio específico",
                            ),
                            ("Afecta otro sitio", "Afecta otro sitio"),
                        ],
                        max_length=100,
                        verbose_name="Extensión Patológica del Tumor (seleccione todo lo que aplique)",
                    ),
                ),
                (
                    "inmunofenotipo",
                    models.CharField(
                        blank=True,
                        max_length=5000,
                        null=True,
                        verbose_name="Inmunofenotipo (IHQ) en la lesión del sitio específico:",
                    ),
                ),
                (
                    "inmunofenotipo_no_realizado",
                    models.BooleanField(verbose_name="Inmunofenotipo no realizado"),
                ),
                (
                    "metodos_y_resultados",
                    models.CharField(
                        blank=True,
                        max_length=5000,
                        null=True,
                        verbose_name="Especifique método (s) y resultados",
                    ),
                ),
                (
                    "puntuacion_pronostico",
                    models.FloatField(verbose_name="Puntuación de Pronóstico"),
                ),
                (
                    "sistema_utilizado",
                    models.CharField(
                        blank=True,
                        max_length=5000,
                        null=True,
                        verbose_name="Especificar el sistema utilizado",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "biopsy",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pathologic_anathomy.biopsyrequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Diagnostico Biopcia de Linfoma",
                "verbose_name_plural": "Diagnosticos Biopcias de Linfoma",
                "ordering": ["id"],
            },
        ),
    ]
