# Generated by Django 4.2.1 on 2023-11-15 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathologic_anathomy', '0046_linfomabiopsydiagnostic'),
    ]

    operations = [
        migrations.AddField(
            model_name='linfomabiopsydiagnostic',
            name='no_especificado_just',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='No especificado(justifique)'),
        ),
        migrations.AlterField(
            model_name='linfomabiopsydiagnostic',
            name='no_especificado',
            field=models.BooleanField(default=False, verbose_name='No especificado'),
        ),
    ]
