# Generated by Django 4.2.1 on 2023-11-15 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathologic_anathomy', '0047_linfomabiopsydiagnostic_no_especificado_just_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='head',
            name='localizacion_tumor',
            field=models.CharField(choices=[('lobulo_derecho', 'El lóbulo derecho'), ('lobulo_izquierdo', 'El lóbulo izquierdo'), ('istmo', 'El istmo'), ('lobulo_piramidal', 'El lóbulo piramidal'), ('otro', 'Otro (especifique)')], max_length=100, verbose_name='El sitio (o localización) del tumor (seleccione todo lo que aplique):'),
        ),
        migrations.AlterField(
            model_name='head',
            name='niveles_ganglionares',
            field=models.CharField(blank=True, choices=[('nivel_Vi', 'Nivel VI: pre- traqueal, para- traqueal y pre-laríngeo/Delphian, peri-tiroideos (disección del compartimiento central)'), ('nivel_VII', 'Nivel VII (los ganglios linfáticos mediastinales superiores)'), ('nivel_IV_derecho', 'Nivel I-V (disección lateral del cuello) Derecho'), ('nivel_IV_izquierdo', 'Nivel I-V (disección lateral del cuello) Izquierda'), ('otros', 'Otros')], max_length=100, null=True, verbose_name='Especifique Niveles Ganglionares (seleccione todo lo que aplique)'),
        ),
    ]
