# Generated by Django 4.2.1 on 2023-11-15 21:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pathologic_anathomy", "0048_alter_head_localizacion_tumor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="head",
            name="localizacion_tumor",
            field=models.CharField(
                max_length=100,
                verbose_name="El sitio (o localización) del tumor (seleccione todo lo que aplique):",
            ),
        ),
        migrations.AlterField(
            model_name="head",
            name="niveles_ganglionares",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Especifique Niveles Ganglionares (seleccione todo lo que aplique)",
            ),
        ),
    ]
