# Generated by Django 4.2.1 on 2023-11-15 22:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "pathologic_anathomy",
            "0050_alter_linfomabiopsydiagnostic_especimen_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="linfomabiopsydiagnostic",
            name="especimen",
            field=models.CharField(
                choices=[
                    ("el ganglio linfático(s)", "El ganglio linfático(s)"),
                    ("otro", "Otro (especifique)"),
                    (
                        "no especificado el procedimiento",
                        "No especificado el procedimiento",
                    ),
                    ("la biopsia", "La biopsia"),
                    ("la resección", "La resección"),
                    ("otro (especifique)", "Otro (especifique)"),
                    ("no especificado", "No especificado"),
                ],
                max_length=100,
                verbose_name="El espécimen (seleccione todo lo que aplique)",
            ),
        ),
        migrations.AlterField(
            model_name="linfomabiopsydiagnostic",
            name="pathologic_tumor_extensions",
            field=models.CharField(
                choices=[
                    ("Afecta la médula ósea", "Afecta la médula ósea"),
                    ("Afecta el sitio específico", "Afecta el sitio específico"),
                    ("Afecta otro sitio", "Afecta otro sitio"),
                ],
                max_length=100,
                verbose_name="Extensión Patológica del Tumor (seleccione todo lo que aplique)",
            ),
        ),
        migrations.AlterField(
            model_name="linfomabiopsydiagnostic",
            name="sitio_tumor",
            field=models.CharField(
                choices=[
                    ("el ganglio linfático(s)", "El ganglio linfático(s)"),
                    ("el sitio no especificado", "El sitio no especificado"),
                ],
                max_length=100,
                verbose_name="El sitio del tumor (seleccione todo lo que aplique)",
            ),
        ),
    ]
