# Generated by Django 3.2.16 on 2023-11-16 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathologic_anathomy', '0053_auto_20231116_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gynecologybiopsydiagnostic',
            name='total_num_nodos_examinados',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número total de Nodo Examinado (el señalizador y el poco señalizador)'),
        ),
    ]
