# Generated by Django 3.2.16 on 2023-11-17 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pathologic_anathomy", "0056_alter_head_aditional_tumor_size"),
    ]

    operations = [
        migrations.CreateModel(
            name="MamaCDIBiopsyDiagnostic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_muestra",
                    models.IntegerField(
                        choices=[
                            (1, "Biopsia con aguja de corte"),
                            (2, "Biopsia por estereotaxia"),
                            (3, "Biopsia guiada por arpón"),
                            (4, "Biopsia excisional Nodulectomía"),
                            (5, "Biopsia excisional Mastectomía parcial"),
                            (6, "Biopsia excisional Cuadrantectomía"),
                            (7, "Biopsia excisional Segmentectomía"),
                            (8, "Re-escisión"),
                            (9, "Mastectomía radical"),
                            (10, "Mastectomía radical post-neoadyuvancia"),
                            (11, "No especificada"),
                            (12, "Otras"),
                        ],
                        verbose_name="Tipo de Muestra",
                    ),
                ),
                (
                    "sitio_tumor_lateralidad",
                    models.CharField(
                        max_length=5000, verbose_name="Sitio del Tumor y Lateralidad"
                    ),
                ),
                (
                    "otra_info_relevante",
                    models.CharField(
                        blank=True,
                        max_length=5000,
                        null=True,
                        verbose_name="Otra información clínica relevante (Dx clínico, resultados de imagen, resultados de laboratorio,  neoadyuvancia)",
                    ),
                ),
                (
                    "medico_asistencia",
                    models.CharField(
                        blank=True,
                        max_length=5000,
                        null=True,
                        verbose_name="Médico de asistencia",
                    ),
                ),
                (
                    "num_muestras_enviadas",
                    models.IntegerField(verbose_name="Numero de muestras enviadas"),
                ),
                (
                    "lateralidad",
                    models.IntegerField(
                        choices=[(1, "Derecha"), (2, "Izquierda"), (3, "Bilateral")],
                        verbose_name="Lateralidad",
                    ),
                ),
                (
                    "reporte_tipo_muestra",
                    models.CharField(
                        blank=True,
                        max_length=5000,
                        null=True,
                        verbose_name="Tipo de Muestra",
                    ),
                ),
                (
                    "diagnóstico_intraoperatorio",
                    models.IntegerField(
                        choices=[(1, "SI"), (2, "NO")],
                        verbose_name="Diagnóstico intraoperatorio",
                    ),
                ),
                (
                    "sitio_tumor",
                    models.CharField(max_length=10, verbose_name="Sitio del Tumor"),
                ),
                (
                    "posicion",
                    models.IntegerField(
                        choices=[
                            (1, "Horas del Reloj"),
                            (2, "No Especificada"),
                            (3, "Otras (especificar)"),
                        ],
                        verbose_name="Diagnóstico intraoperatorio",
                    ),
                ),
                (
                    "posicion_otra",
                    models.CharField(
                        blank=True,
                        max_length=5000,
                        null=True,
                        verbose_name="Otra posición(especificar)",
                    ),
                ),
                (
                    "orientacion_especimen",
                    models.IntegerField(
                        choices=[
                            (1, "Marcaje y sitio al que corresponde"),
                            (2, "No orientado"),
                        ],
                        verbose_name="Orientación del espécimen",
                    ),
                ),
                (
                    "orientacion_sitio",
                    models.CharField(
                        blank=True,
                        max_length=5000,
                        null=True,
                        verbose_name=" Orientación del espécimen. Sitio al que corresponde",
                    ),
                ),
                (
                    "metodo_localizacion",
                    models.CharField(
                        max_length=5000, verbose_name="Método de localización"
                    ),
                ),
                (
                    "especimen_size",
                    models.CharField(
                        max_length=100, verbose_name="Tamaño del espécimen(mm o cm)"
                    ),
                ),
                (
                    "tumor_macro_visible",
                    models.IntegerField(
                        choices=[
                            (1, "Ausente"),
                            (2, "Presente(Indicar el Número de focos )"),
                        ],
                        verbose_name="Tumor macroscópicamente visible",
                    ),
                ),
                (
                    "num_focos_presentes",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Número de focos presentes"
                    ),
                ),
                (
                    "decripcion_macro_tumor",
                    models.CharField(
                        blank=True,
                        max_length=5000,
                        null=True,
                        verbose_name="Descripción macroscópica del tumor(es)",
                    ),
                ),
                (
                    "tumor_size",
                    models.CharField(
                        max_length=100, verbose_name="Tamaño del tumor(es)(mm o cm)"
                    ),
                ),
                (
                    "distancia_foco_tumoral",
                    models.FloatField(
                        verbose_name="Distancia del foco tumoral más cercano"
                    ),
                ),
                (
                    "distancia_tumor_margenes",
                    models.FloatField(
                        verbose_name="Distancia del tumor(es) de los márgenes quirúrgicos(mm)"
                    ),
                ),
                ("piel_presente", models.BooleanField(verbose_name="Piel presente")),
                (
                    "piel_presente_dimenciones",
                    models.CharField(
                        max_length=100,
                        verbose_name="Dimensiones(__x__(mm)) de la piel en caso de estar presente:",
                    ),
                ),
                (
                    "alteraciones",
                    models.CharField(
                        blank=True,
                        max_length=5000,
                        null=True,
                        verbose_name="Alteraciones",
                    ),
                ),
                (
                    "musculo_presente",
                    models.BooleanField(verbose_name="Musculo presente"),
                ),
                (
                    "si_ganglio_linfatico_report",
                    models.CharField(
                        blank=True, max_length=100000, null=True, verbose_name=""
                    ),
                ),
                (
                    "ganglios_linfaticos_no_centinelas",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Ganglios linfáticos no centinelas",
                    ),
                ),
                (
                    "num_total_ganglios",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Número total de ganglios"
                    ),
                ),
                (
                    "average_size",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Tamaño promedio (mm o cm )"
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(
                        blank=True,
                        max_length=5000,
                        null=True,
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "otros_hallazgos_macros",
                    models.CharField(
                        blank=True,
                        max_length=5000,
                        null=True,
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "relacion_cortes",
                    models.CharField(
                        blank=True,
                        max_length=5000,
                        null=True,
                        verbose_name="Relación de cortes",
                    ),
                ),
                (
                    "reportado_por",
                    models.CharField(
                        blank=True,
                        max_length=5000,
                        null=True,
                        verbose_name="Reportado por",
                    ),
                ),
                (
                    "tumores_multiples_presentes",
                    models.CharField(
                        blank=True,
                        max_length=5000,
                        null=True,
                        verbose_name="Tumores múltiples , si están presentes",
                    ),
                ),
                (
                    "cuadrantes_involucrados",
                    models.CharField(
                        blank=True,
                        max_length=5000,
                        null=True,
                        verbose_name="Cuadrantes involucrados",
                    ),
                ),
                (
                    "num_total_focos_tumorales",
                    models.IntegerField(verbose_name="Número total de focos tumorales"),
                ),
                (
                    "max_size_by_tumor",
                    models.CharField(
                        max_length=5000,
                        verbose_name="Para cada tumor identificado, tamaño máximo(mm)",
                    ),
                ),
                (
                    "tipo_histologico",
                    models.IntegerField(
                        choices=[
                            (
                                1,
                                "Carcinoma ductal infiltrante sin otra especificación (SOE)",
                            ),
                            (2, "Carcinoma micro-infiltrante"),
                            (3, "Carcinoma lobular infiltrante"),
                            (4, "Carcinoma infiltrante con cambios lobulares"),
                            (
                                5,
                                "Carcinoma infiltrante con cambios ductales and lobulares (“carcinoma tipo mixto”)",
                            ),
                            (6, "Carcinoma mucinoso"),
                            (7, "Carcinoma tubular"),
                            (8, "Carcinoma invasivo, variante tubulo-lobular"),
                            (9, "Carcinoma invasivo cribriforme"),
                            (10, "Carcinoma invasivo micropapilar"),
                            (11, "Carcinoma invasivo papillar"),
                            (12, "Carcinoma medular"),
                            (13, "Carcinoma invasivo con cambios medulares"),
                            (14, "Carcinoma metaplàsico"),
                            (15, "Carcinoma adenoescamoso de bajo grado"),
                            (16, "Carcinoma fibromatosis-like metaplastic"),
                            (17, "Carcinoma metaplàsico, spindle cell type"),
                            (
                                18,
                                "Carcinoma metaplàsico typo mixto epithelial and mesenquimatoso",
                            ),
                            (19, "Carcinoma Invasive con cambios metaplàsico"),
                            (20, "Carcinoma de células escamosas"),
                            (21, "Carcinoma adenoideo quístico"),
                            (22, "Carcinoma invasivo con cambios apocrinos"),
                            (
                                23,
                                "Carcinoma invasivo concambios clear cell (glycogen rich)",
                            ),
                            (24, "Carcinoma invasivo with neuroendocrine features"),
                            (
                                25,
                                "Carcinoma invasive con células en anillo de sello features",
                            ),
                            (26, "Carcinoma secretor"),
                            (27, "Carcinoma Invasive, type cannot be determined"),
                            (28, "Carcinoma invasive no residual"),
                            (29, "Otros tipos histológicos"),
                        ],
                        verbose_name="Tipo Histologico",
                    ),
                ),
                (
                    "tipo_histologico_otros",
                    models.CharField(
                        blank=True,
                        max_length=5000,
                        null=True,
                        verbose_name="Otros Tipos Histologicos(especifique)",
                    ),
                ),
                (
                    "grado_histologico",
                    models.CharField(
                        max_length=1000,
                        verbose_name="Grado histológico(Nottingham Histologic Score)",
                    ),
                ),
                (
                    "diferenciacion_glandular",
                    models.CharField(
                        max_length=1000,
                        verbose_name="Diferenciación Glandular (Acinar)/Tubular",
                    ),
                ),
                (
                    "pleomorfismo_nuclear",
                    models.CharField(
                        max_length=1000, verbose_name="Pleomorfismo Nuclear"
                    ),
                ),
                ("indice_mitotico", models.FloatField(verbose_name="Indice Mitótico")),
                (
                    "invasion_linfovascular",
                    models.IntegerField(
                        choices=[
                            (1, "Not identificada"),
                            (2, "Presente"),
                            (3, "No pudo ser determinada"),
                        ],
                        verbose_name="Invasión linfovascular",
                    ),
                ),
                (
                    "invasion_linfovascular_dermica",
                    models.IntegerField(
                        choices=[
                            (1, "Piel no presente"),
                            (2, "No identificada"),
                            (3, "Presente"),
                            (4, "No pudo ser determinada"),
                        ],
                        verbose_name="Invasión linfovascular dérmica",
                    ),
                ),
                (
                    "necrosis",
                    models.IntegerField(
                        choices=[
                            (1, "Not identified"),
                            (
                                2,
                                "Presente, focal (foco pequeños o necrosis celular aislada)",
                            ),
                            (3, "Presente, central (necrosis expansive “comedo”)"),
                        ],
                        verbose_name="Necrosis",
                    ),
                ),
                (
                    "fibrosis_intratumoral",
                    models.IntegerField(
                        choices=[
                            (1, "No identificada"),
                            (2, "Presente"),
                            (3, "Sospechosa"),
                        ],
                        verbose_name="Fibrosis Intratumoral",
                    ),
                ),
                (
                    "desmoplasia_intratumoral",
                    models.IntegerField(
                        choices=[
                            (1, "No identificada"),
                            (2, "Presente"),
                            (3, "Sospechosa"),
                        ],
                        verbose_name="Desmoplasia Intratumoral",
                    ),
                ),
                (
                    "infiltrado_mononuclear_intratumoral",
                    models.IntegerField(
                        choices=[
                            (1, "Ausente"),
                            (2, "Presente"),
                            (3, "Sospechosa"),
                            (4, "Otro tipo celular (especificar)"),
                        ],
                        verbose_name="Infiltrado mononuclear intratumoral",
                    ),
                ),
                (
                    "infiltrado_mononuclear_intratumoral_otro",
                    models.CharField(
                        blank=True,
                        max_length=5000,
                        null=True,
                        verbose_name="Otro tipo celular(especifique)",
                    ),
                ),
                (
                    "infiltrado_mononuclear_peritumoral",
                    models.IntegerField(
                        choices=[
                            (1, "Ausente"),
                            (2, "Presente"),
                            (3, "Sospechosa"),
                            (4, "Otro tipo celular (especificar)"),
                        ],
                        verbose_name="Infiltrado mononuclear peritumoral",
                    ),
                ),
                (
                    "infiltrado_mononuclear_peritumoral_otro",
                    models.CharField(
                        blank=True,
                        max_length=5000,
                        null=True,
                        verbose_name="Otro tipo celular(especifique)",
                    ),
                ),
                (
                    "presencia_dcis",
                    models.IntegerField(
                        choices=[
                            (1, "No DCIS en la muestra"),
                            (
                                2,
                                "DCIS presente.Negative for extensive intraductal component (EIC)",
                            ),
                            (3, "DCIS presente.Positive for EIC"),
                            (
                                4,
                                "DCIS presente.Solo presente después de tto presurgical (neoadjuvant)",
                            ),
                        ],
                        verbose_name="Presencia de Carcinoma Ductal In Situ (DCIS)",
                    ),
                ),
                (
                    "cdis_size",
                    models.FloatField(
                        verbose_name="Tamaño (extensión) del CDIS (mayor dimensión usando la evaluación macro and microscópica) (milímetros)"
                    ),
                ),
                (
                    "adittional_size",
                    models.FloatField(
                        verbose_name="Dimensions adicionales (millimeters)"
                    ),
                ),
                (
                    "num_bloques_cdis",
                    models.IntegerField(verbose_name="Número de bloques con CDIS"),
                ),
                (
                    "num_bloques_examinados",
                    models.IntegerField(verbose_name="Número de bloques examinados"),
                ),
                (
                    "patron_arquitectural",
                    models.CharField(
                        blank=True,
                        max_length=5000,
                        null=True,
                        verbose_name="Otro Patrón arquitectural(especifique)",
                    ),
                ),
                (
                    "grado",
                    models.IntegerField(
                        choices=[
                            (1, "Grado I (low)"),
                            (2, "Grado II (intermediate)"),
                            (3, "Grado III (high)"),
                        ],
                        verbose_name="Grado",
                    ),
                ),
                (
                    "lcis_presente",
                    models.BooleanField(
                        verbose_name="Lobular Carcinoma In Situ(LCIS) Presente"
                    ),
                ),
                (
                    "extension_tumoral_piel",
                    models.IntegerField(
                        choices=[
                            (
                                1,
                                "Invade directamente la dermis o epidermis sin ulceración",
                            ),
                            (
                                2,
                                "Invade directamente la dermis o epidermis con ulceración",
                            ),
                            (3, "Presencia de focos satélites"),
                        ],
                        verbose_name="Extensión tumoral a la piel",
                    ),
                ),
                (
                    "pezones_afectados",
                    models.IntegerField(
                        verbose_name="Pezones Afectado por CDIS (Enf Paget)"
                    ),
                ),
                (
                    "invasion_musculo",
                    models.BooleanField(verbose_name="Invasión a músculo"),
                ),
                (
                    "invasion_musculo_pared_torxacica",
                    models.BooleanField(
                        verbose_name="Invasión Músculo y pared toráxcica"
                    ),
                ),
                (
                    "margenes",
                    models.IntegerField(
                        choices=[
                            (1, "No pueden ser evaluados"),
                            (2, "No afectados"),
                            (3, "Positive para carcinoma invasivo"),
                        ]
                    ),
                ),
                (
                    "distancia_a_los_margenes",
                    models.FloatField(verbose_name="Distancia a los Márgenes"),
                ),
                (
                    "margen_anterior",
                    models.CharField(max_length=1000, verbose_name="Anterior"),
                ),
                (
                    "margen_posterior",
                    models.CharField(
                        blank=True, max_length=1000, null=True, verbose_name="Posterior"
                    ),
                ),
                (
                    "margen_superior",
                    models.CharField(
                        blank=True, max_length=1000, null=True, verbose_name="Superior"
                    ),
                ),
                (
                    "margen_inferior",
                    models.CharField(
                        blank=True, max_length=1000, null=True, verbose_name="Inferior"
                    ),
                ),
                (
                    "margen_medial",
                    models.CharField(
                        blank=True, max_length=1000, null=True, verbose_name="Medial"
                    ),
                ),
                (
                    "margen_lateral",
                    models.CharField(
                        blank=True, max_length=1000, null=True, verbose_name="Lateral"
                    ),
                ),
                (
                    "margen_otros",
                    models.CharField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="Otros márgenes(especificar)",
                    ),
                ),
                (
                    "margenes_con_cdis",
                    models.IntegerField(
                        choices=[
                            (1, "No pueden ser evaluados"),
                            (2, "No CDIS en la muestra"),
                            (3, "Positive para CDIS"),
                        ],
                        verbose_name="Márgenes con CDIS",
                    ),
                ),
                (
                    "distancia",
                    models.FloatField(verbose_name="Distancia a los márgenes (mm): "),
                ),
                (
                    "margen_anterior_cdis",
                    models.CharField(
                        blank=True, max_length=1000, null=True, verbose_name="Anterior"
                    ),
                ),
                (
                    "margen_posterior_cdis",
                    models.CharField(
                        blank=True, max_length=1000, null=True, verbose_name="Posterior"
                    ),
                ),
                (
                    "margen_superior_cdis",
                    models.CharField(
                        blank=True, max_length=1000, null=True, verbose_name="Superior"
                    ),
                ),
                (
                    "margen_inferior_cdis",
                    models.CharField(max_length=1000, verbose_name="Inferior"),
                ),
                (
                    "margen_medial_cdis",
                    models.CharField(
                        blank=True, max_length=1000, null=True, verbose_name="Medial"
                    ),
                ),
                (
                    "margen_lateral_cdis",
                    models.CharField(
                        blank=True, max_length=1000, null=True, verbose_name="Lateral"
                    ),
                ),
                (
                    "margen_otros_cdis",
                    models.CharField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="Otros márgenes(especificar)",
                    ),
                ),
                (
                    "num_gang_linf_reg_not_send",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Ganglios Linfáticos Regionales no enviados",
                    ),
                ),
                (
                    "num_gang_linf_reg_not_found",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Ganglios Linfáticos Regionales no encontrados",
                    ),
                ),
                (
                    "num_gang_linf_reg_not_determinated",
                    models.CharField(
                        blank=True,
                        max_length=5000,
                        null=True,
                        verbose_name="Número de ganglios linfáticos que no pudieron ser determinados (explicar)",
                    ),
                ),
                (
                    "num_gang_linf_reg_examinated",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Ganglios Linfáticos Regionales examinados",
                    ),
                ),
                (
                    "num_gang_linf_macro_mayor2",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Número de  ganglios linfáticos con macro metástasis (>2 mm)",
                    ),
                ),
                (
                    "num_gang_linf_macro_mayor02",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Número de  ganglios linfáticos con micro metástasis (>0.2 mm to 2 mm y/o >200 células)",
                    ),
                ),
                (
                    "num_gang_linf_macro_mayor02_aisladas",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Tamaño de los mayores depósitos metastásicos(mm)",
                    ),
                ),
                (
                    "extension_extraganglionar",
                    models.IntegerField(
                        choices=[
                            (1, "No identificada"),
                            (2, "Presente"),
                            (3, "No puede ser determinada"),
                        ],
                        verbose_name="Extensión extraganglionar:",
                    ),
                ),
                (
                    "num_gang_centinelas_examinated",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Número de  ganglios centinelas examined(si proceder):",
                    ),
                ),
                (
                    "efecto_tratamiento",
                    models.IntegerField(
                        choices=[
                            (1, "Tratamiento pre quirúrgico no conocido"),
                            (2, "No se define respuesta a tratamiento pre quirúrgico"),
                            (
                                3,
                                "Respuesta probable o definida a tratamiento pre quirúrgico",
                            ),
                            (
                                4,
                                "No carcinoma residual invasor luego de tratamiento pre qqco",
                            ),
                        ],
                        verbose_name="Efectos del tratamiento en el tumor(si neoadyuvancia)",
                    ),
                ),
                (
                    "efectos_tratamiento_gl",
                    models.IntegerField(
                        choices=[
                            (1, "No exéresis de GL."),
                            (2, "No se define respuesta a tto pre quirúrgico"),
                            (
                                3,
                                "Respuesta probable o definida response a tto pre quirúrgico",
                            ),
                            (
                                4,
                                "No GL metastásicos. Cicatriz fibrosa posiblemente en relación con metástasis con respuesta patológica completa.",
                            ),
                            (5, "No GL metastásicos y no cicatriz fibrosa"),
                        ],
                        verbose_name="Efectos del tratamiento en los GL (si neoadyuvancia)",
                    ),
                ),
                (
                    "efecto_tratamiento_realizado",
                    models.IntegerField(
                        choices=[
                            (1, "Sin respuesta"),
                            (2, "Respuesta parcial"),
                            (3, "Respuesta completa"),
                        ],
                        verbose_name="Efecto del tratamiento (después de neoadyuvancia hormonal o quimioterapia si se hubiera realizado)",
                    ),
                ),
                (
                    "porciento_celularidad_cancer",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Si hubo respuesta parcial .Indique el % de celularidad del cáncer invasor ",
                    ),
                ),
                (
                    "sistema_evaluacion_respuesta_utilizado",
                    models.CharField(
                        blank=True,
                        max_length=5000,
                        null=True,
                        verbose_name="Especificar sistema de evaluación de respuesta a la neoadyuvancia utilizado",
                    ),
                ),
                (
                    "otros_estudios_ihq",
                    models.CharField(
                        blank=True,
                        max_length=5000,
                        null=True,
                        verbose_name="Otros estudios: IHQ",
                    ),
                ),
                (
                    "comentarios",
                    models.CharField(
                        blank=True,
                        max_length=5000,
                        null=True,
                        verbose_name="Comentarios",
                    ),
                ),
                (
                    "diagnosticado_por",
                    models.CharField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="Diagnosticado por",
                    ),
                ),
                ("reated_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "biopsy",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="biopsy_diagnostic_mama_cdi",
                        to="pathologic_anathomy.biopsyrequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Diagnostico Biopcia de Mama(CDI)",
                "verbose_name_plural": "Diagnosticos Biopcias de Mama(CDI)",
                "ordering": ["id"],
            },
        ),
    ]
