# Generated by Django 3.2.16 on 2023-11-19 11:57

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pathologic_anathomy', '0060_alter_mamacdibiopsydiagnostic_margen_inferior_cdis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gynecologybiopsydiagnostic',
            name='margen_ectocervical_afectado_por',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('INFILTRADO', 'Infiltrado por carcinoma invasor. Especifique posición, si es posible:'), ('NEOPLASIA', 'Neoplasia intraepithelial'), ('LESION', 'Lesión escamosa (CIN 2-3)'), ('ADENOCARCINOMA', 'Adenocarcinoma en situ')], default=None, max_length=100, verbose_name='Afectado por:'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gynecologybiopsydiagnostic',
            name='margen_endocervical_afectado_por',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('INFILTRADO', 'Infiltrado por carcinoma invasor. Especifique posición, si es posible:'), ('NEOPLASIA', 'Neoplasia intraepithelial'), ('LESION', 'Lesión escamosa (CIN 2-3)'), ('ADENOCARCINOMA', 'Adenocarcinoma en situ')], default=None, max_length=100, verbose_name='Afectado por:'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gynecologybiopsydiagnostic',
            name='margen_profundo_afectado_por',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('INFILTRADO', 'Infiltrado por carcinoma invasor. Especifique posición, si es posible:'), ('NEOPLASIA', 'Neoplasia intraepithelial'), ('LESION', 'Lesión escamosa (CIN 2-3)'), ('ADENOCARCINOMA', 'Adenocarcinoma en situ')], default=None, max_length=100, verbose_name='Afectado por:'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gynecologybiopsydiagnostic',
            name='otra_patologia_asociada',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('NO_IDENTIFICO', 'No identificó'), ('NIC_I', 'NIC I'), ('NIC_II', 'NIC II'), ('INFLAMACION', 'Inflamación'), ('OTRO', 'Otro del + (especifique)')], max_length=100, verbose_name='Otra patología asociada(seleccione todo lo que aplique)'),
        ),
        migrations.AlterField(
            model_name='gynecologybiopsydiagnostic',
            name='sitio_tumor',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('CUADRANTE_SUPERIOR_DERECHO', 'Cuadrante superior, derecho'), ('CUADRANTE_SUPERIOR_IZQUIERDO', 'Cuadrante superior, izquierdo'), ('CUADRANTE_INFERIOR_DERECHO', 'Cuadrante inferior, derecho'), ('CUADRANTE_INFERIOR_IZQUIERDO', 'Cuadrante inferior, izquierdo'), ('NO_DETERMINADO', 'No puede ser determinado (explique)')], max_length=100, verbose_name='El sitio del Tumor (seleccione todo lo que aplique)'),
        ),
    ]
