# Generated by Django 3.2.16 on 2023-11-19 12:09

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pathologic_anathomy", "0061_auto_20231119_0657"),
    ]

    operations = [
        migrations.AlterField(
            model_name="head",
            name="localizacion_tumor",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("lobulo_derecho", "El lóbulo derecho"),
                    ("lobulo_izquierdo", "El lóbulo izquierdo"),
                    ("istmo", "El istmo"),
                    ("lobulo_piramidal", "El lóbulo piramidal"),
                    ("otro", "Otro (especifique)"),
                ],
                max_length=100,
                verbose_name="El sitio (o localización) del tumor (seleccione todo lo que aplique):",
            ),
        ),
        migrations.AlterField(
            model_name="head",
            name="niveles_ganglionares",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    (
                        "nivel_Vi",
                        "Nivel VI: pre- traqueal, para- traqueal y pre-laríngeo/Delphian, peri-tiroideos (disección del compartimiento central)",
                    ),
                    (
                        "nivel_VII",
                        "Nivel VII (los ganglios linfáticos mediastinales superiores)",
                    ),
                    (
                        "nivel_IV_derecho",
                        "Nivel I-V (disección lateral del cuello) Derecho",
                    ),
                    (
                        "nivel_IV_izquierdo",
                        "Nivel I-V (disección lateral del cuello) Izquierda",
                    ),
                    ("otros", "Otros"),
                ],
                default=None,
                max_length=100,
                verbose_name="Especifique Niveles Ganglionares (seleccione todo lo que aplique)",
            ),
            preserve_default=False,
        ),
    ]
