# Generated by Django 3.2.16 on 2023-11-19 13:12

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pathologic_anathomy", "0062_auto_20231119_0709"),
    ]

    operations = [
        migrations.AlterField(
            model_name="linfomabiopsydiagnostic",
            name="especimen",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("el ganglio linfático(s)", "El ganglio linfático(s)"),
                    (
                        "no especificado el procedimiento",
                        "No especificado el procedimiento",
                    ),
                    ("la biopsia", "La biopsia"),
                    ("la resección", "La resección"),
                    ("otro", "Otro (especifique)"),
                    ("no especificado", "No especificado"),
                ],
                max_length=100,
                verbose_name="El espécimen (seleccione todo lo que aplique)",
            ),
        ),
        migrations.AlterField(
            model_name="linfomabiopsydiagnostic",
            name="pathologic_tumor_extensions",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("Afecta la médula ósea", "Afecta la médula ósea"),
                    ("Afecta el sitio específico", "Afecta el sitio específico"),
                    ("Afecta otro sitio", "Afecta otro sitio"),
                ],
                max_length=100,
                verbose_name="Extensión Patológica del Tumor (seleccione todo lo que aplique)",
            ),
        ),
        migrations.AlterField(
            model_name="linfomabiopsydiagnostic",
            name="sitio_tumor",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("el ganglio linfático(s)", "El ganglio linfático(s)"),
                    ("el sitio no especificado", "El sitio no especificado"),
                ],
                max_length=100,
                verbose_name="El sitio del tumor (seleccione todo lo que aplique)",
            ),
        ),
    ]
