# Generated by Django 3.2.16 on 2023-11-19 15:52

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pathologic_anathomy', '0063_auto_20231119_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mamacdibiopsydiagnostic',
            name='sitio_tumor',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('CLS', 'Cuadrante lateral superior'), ('CLI', 'Cuadrante lateral inferior'), ('CMS', 'Cuadrante medial superior'), ('CMI', 'Cuadrante medial inferior'), ('CEN', 'Central'), ('PEZ', 'Pezón')], max_length=10, verbose_name='Sitio del Tumor'),
        ),
    ]
