# Generated by Django 3.2.16 on 2023-11-19 19:13

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pathologic_anathomy", "0064_alter_mamacdibiopsydiagnostic_sitio_tumor"),
    ]

    operations = [
        migrations.CreateModel(
            name="MamaCDISBiopsyDiagnostic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_muestra",
                    models.IntegerField(
                        choices=[
                            (1, "Biopsia con aguja de corte"),
                            (2, "Biopsia por estereotaxia"),
                            (3, "Biopsia guiada por arpón"),
                            (4, "Biopsia excisional Nodulectomía"),
                            (5, "Biopsia excisional Mastectomía parcial"),
                            (6, "Biopsia excisional Cuadrantectomía"),
                            (7, "Biopsia excisional Segmentectomía"),
                            (8, "Re-escisión"),
                            (9, "Mastectomía radical"),
                            (10, "Mastectomía radical post-neoadyuvancia"),
                            (11, "No especificada"),
                            (12, "Otras"),
                        ],
                        verbose_name="Tipo de Muestra",
                    ),
                ),
                (
                    "sitio_tumor_lateralidad",
                    models.CharField(
                        max_length=5000, verbose_name="Sitio del Tumor y Lateralidad"
                    ),
                ),
                (
                    "metodo_localizacion",
                    models.IntegerField(
                        choices=[(1, "Tumor nuevo primario"), (2, "Recurrencia")],
                        verbose_name="Método de localización",
                    ),
                ),
                (
                    "historia_clinica_actual",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            ("MP", "Masa palpable"),
                            ("HR", "Hallazgos Radiológicos"),
                            (
                                "MD",
                                "Hallazgos Radiológicos. Masa o distorsión arquitectural",
                            ),
                            ("CA", "Hallazgos Radiológicos. Calcificaciones"),
                            ("OH", "Hallazgos Radiológicos otros"),
                            ("DP", "Descarga por el Pezón"),
                            ("OT", "Otra"),
                            ("HP", "Historia previa de cáncer de mama"),
                        ],
                        max_length=100,
                        verbose_name="Historia Clínica actual (todas las que apliquen)",
                    ),
                ),
                (
                    "hallazgos_radiologicos_otros",
                    models.CharField(
                        blank=True,
                        max_length=5000,
                        null=True,
                        verbose_name="Hallazgos Radiológicos otros",
                    ),
                ),
                (
                    "historia_clinica_otro",
                    models.CharField(
                        blank=True,
                        max_length=5000,
                        null=True,
                        verbose_name="Otra Historia Clínica actual",
                    ),
                ),
                (
                    "esp_local_diagnost_tratam",
                    models.CharField(
                        max_length=5000,
                        verbose_name="Especificar localización, diagnóstico, y tratamiento anterior",
                    ),
                ),
                (
                    "medico_asistencia",
                    models.CharField(
                        max_length=1000, verbose_name="Médico de asistencia"
                    ),
                ),
                (
                    "identificacion_muestra",
                    models.IntegerField(
                        choices=[
                            (0, "Excisional"),
                            (1, "Mastectomía total"),
                            (2, "No especificada"),
                            (3, "Otra (especificar)"),
                        ],
                        verbose_name="Identificación de la muestra",
                    ),
                ),
                (
                    "identificacion_muestra_otro",
                    models.CharField(
                        blank=True,
                        max_length=5000,
                        null=True,
                        verbose_name="Otra Identificación de la muestra",
                    ),
                ),
                (
                    "lateralidad",
                    models.IntegerField(
                        choices=[
                            (0, "Derecha"),
                            (1, "Izquierda"),
                            (2, "Bilateral"),
                            (3, "No especificada"),
                        ],
                        verbose_name="Lateralidad",
                    ),
                ),
                (
                    "sitio_tumor",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            ("CLS", "Cuadrante lateral superior"),
                            ("CLI", "Cuadrante lateral inferior"),
                            ("CMS", "Cuadrante medial superior"),
                            ("CMI", "Cuadrante medial inferior"),
                            ("CEN", "Central"),
                            ("PEZ", "Pezón"),
                        ],
                        max_length=100,
                        verbose_name="Sitio Tumor (seleccione todos los que apliquen)",
                    ),
                ),
                (
                    "posicion",
                    models.IntegerField(
                        choices=[
                            (0, "Horas del reloj"),
                            (1, "No especificada"),
                            (2, "Otras (especificar)"),
                        ],
                        verbose_name="Posicion",
                    ),
                ),
                (
                    "otra_posicion",
                    models.CharField(
                        blank=True,
                        max_length=5000,
                        null=True,
                        verbose_name="Otra Posición",
                    ),
                ),
                (
                    "extension_maxima_cdi",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Extensión máxima del CDI (mm)",
                    ),
                ),
                (
                    "dimensiones_adicionales_cdi",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Extensiones adicionales del CDI (mm)",
                    ),
                ),
                (
                    "num_bloques_cdi",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Número de bloques son CDIS"
                    ),
                ),
                (
                    "num_bloques_examinados",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="",
                        verbose_name="Número de bloques examinados",
                    ),
                ),
                (
                    "reportado_por",
                    models.CharField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="Reportado por",
                    ),
                ),
                (
                    "patron_arquitectural",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            ("COMEDO", "Comedo"),
                            ("PAGET", "Paget disease"),
                            ("CRIBRIFORME", "Cribriform"),
                            ("MICROPAPILAR", "Micropapillary"),
                            ("PAPILAR", "Papillary"),
                            ("SOLIDO", "Solid"),
                            ("OTRO", "Otro (especificar)"),
                        ],
                        max_length=100,
                        verbose_name="Patron Arquitectural(todos los que apliquen)",
                    ),
                ),
                (
                    "patron_arquitectural_otro",
                    models.CharField(
                        blank=True,
                        max_length=5000,
                        null=True,
                        verbose_name="Otro Patron Arquitectural",
                    ),
                ),
                (
                    "grado_nuclear",
                    models.IntegerField(
                        choices=[
                            (0, "Grado I (bajo)"),
                            (1, "Grado II (intermedio)"),
                            (2, "Grado III (alto)"),
                        ],
                        verbose_name="Grado Nuclear",
                    ),
                ),
                (
                    "heterogeneidad_grado_nuclear",
                    models.IntegerField(
                        choices=[
                            (1, "Ausente"),
                            (2, "Presente - Baja"),
                            (3, "Presente - Intermedia"),
                            (4, "Presente - Alta"),
                        ],
                        verbose_name="Heterogeneidad del grado nuclear",
                    ),
                ),
                (
                    "necrosis",
                    models.IntegerField(
                        choices=[
                            (0, "No identificada"),
                            (1, "Presente, focal"),
                            (2, "Presente, central"),
                        ],
                        verbose_name="Necrosis",
                    ),
                ),
                (
                    "microcalcificaciones1",
                    models.IntegerField(
                        choices=[
                            (1, "Ausente"),
                            (2, "Presente en el propio CDIS"),
                            (3, "Presente en tejido benigno"),
                        ],
                        verbose_name="Microcalcificaciones",
                    ),
                ),
                (
                    "size_extension",
                    models.CharField(
                        max_length=1000, verbose_name="Tamaño y extensión:"
                    ),
                ),
                (
                    "enfermedad_paget",
                    models.IntegerField(
                        choices=[(1, "Ausente"), (2, "Presente")],
                        verbose_name="Enfermedad de Paget",
                    ),
                ),
                (
                    "neoplasia_lobular",
                    models.IntegerField(
                        choices=[
                            (1, "Ausente"),
                            (2, "Presente - Clásica"),
                            (3, "Presente - Variante"),
                            (4, "Presente en el margen"),
                        ],
                        verbose_name="Neoplasia lobular",
                    ),
                ),
                (
                    "margenes",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            ("NPE", "No puede ser evaluado"),
                            ("PPC", "Positivo para CDIS"),
                            ("PPD", "Positivo para CDI"),
                            ("PPY", "Positivo para CDIS y CDI"),
                            ("NAP", "No afectado por CDIS"),
                        ],
                        max_length=100,
                        verbose_name="Márgenes (todos los que apliquen)",
                    ),
                ),
                (
                    "distancia_margen_mas_cercano",
                    models.FloatField(
                        verbose_name="Distancia del margen más cercano(mm)"
                    ),
                ),
                (
                    "margen_mas_cercano",
                    models.CharField(
                        max_length=5000, verbose_name="Márgen mas cercano"
                    ),
                ),
                (
                    "diastancia_margen_superior",
                    models.FloatField(verbose_name="Distancia al márgen superior(mm)"),
                ),
                (
                    "diastancia_margen_inferior",
                    models.FloatField(verbose_name="Distancia al márgen inferior(mm)"),
                ),
                (
                    "diastancia_margen_medial",
                    models.FloatField(verbose_name="Distancia al márgen medial(mm)"),
                ),
                (
                    "diastancia_margen_lateral",
                    models.FloatField(verbose_name="Distancia al márgen lateral(mm)"),
                ),
                (
                    "diastancia_margen_anterior",
                    models.FloatField(verbose_name="Distancia al márgen anterior(mm)"),
                ),
                (
                    "diastancia_margen_posterior",
                    models.FloatField(verbose_name="Distancia al márgen posterior(mm)"),
                ),
                (
                    "distancia_otros_margenes",
                    models.CharField(
                        blank=True,
                        max_length=5000,
                        null=True,
                        verbose_name="Distancia otros márgenes especificados",
                    ),
                ),
                (
                    "margen_especificado_especific",
                    models.CharField(
                        blank=True,
                        max_length=5000,
                        null=True,
                        verbose_name="Margen especificado",
                    ),
                ),
                (
                    "margen_especificado_determ",
                    models.IntegerField(
                        choices=[(1, "Positivo para CDIS"), (2, "No determinado")],
                        verbose_name="Margen especificado",
                    ),
                ),
                (
                    "margenes_positivos_anterior_size",
                    models.FloatField(
                        verbose_name="Para márgenes positivos, especificar extensión (focal, minima/moderate, or extensiva): Anterior"
                    ),
                ),
                (
                    "margenes_positivos_posterior_size",
                    models.FloatField(
                        verbose_name="Para márgenes positivos, especificar extensión (focal, minima/moderate, or extensiva): Posterior"
                    ),
                ),
                (
                    "margenes_positivos_superior_size",
                    models.FloatField(
                        verbose_name="Para márgenes positivos, especificar extensión (focal, minima/moderate, or extensiva): SUperior"
                    ),
                ),
                (
                    "margenes_positivos_inferior_size",
                    models.FloatField(
                        verbose_name="Para márgenes positivos, especificar extensión (focal, minima/moderate, or extensiva): Inferior"
                    ),
                ),
                (
                    "margenes_positivos_medial_size",
                    models.FloatField(
                        verbose_name="Para márgenes positivos, especificar extensión (focal, minima/moderate, or extensiva): Medial"
                    ),
                ),
                (
                    "margenes_positivos_lateral_size",
                    models.FloatField(
                        verbose_name="Para márgenes positivos, especificar extensión (focal, minima/moderate, or extensiva): Lateral"
                    ),
                ),
                (
                    "margenes_positivos_otros",
                    models.CharField(
                        blank=True,
                        max_length=5000,
                        null=True,
                        verbose_name="Otros Márgenes(especificar)",
                    ),
                ),
                (
                    "ganglios_linfaticos",
                    models.IntegerField(
                        choices=[(1, "No enviados"), (2, "No identificados")],
                        verbose_name="Ganglios Linfáticos Regionales",
                    ),
                ),
                (
                    "num_ganglios_linfaticos_no_determ",
                    models.CharField(
                        blank=True,
                        max_length=5000,
                        null=True,
                        verbose_name="Número de ganglios linfáticos que no pudieron ser determinados (explicar)",
                    ),
                ),
                (
                    "num_ganglios_linfaticos_exam",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name=" Número de ganglios linfáticos examinados",
                    ),
                ),
                (
                    "num_ganglios_linfaticos_hig_2",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Número de ganglios linfáticos con macro metástasis (>2 mm)",
                    ),
                ),
                (
                    "num_ganglios_linfaticos_hig_200",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Número de ganglios linfáticos con micro metástasis (>0.2 mm to 2 mm y/o >200 células)",
                    ),
                ),
                (
                    "num_ganglios_linfaticos_low_200",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Número de ganglios linfáticos con células tumorales aisldas (≤0.2mm y/o ≤200 células)",
                    ),
                ),
                (
                    "size_depositos_metastaticos",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Tamaño de los mayores depósitos metastásicos(mm)",
                    ),
                ),
                (
                    "extension_extraganglionar",
                    models.IntegerField(
                        choices=[
                            (0, "No identificada"),
                            (1, "Presente"),
                            (2, "No puede ser determinada"),
                        ],
                        verbose_name="Extensión extraganglionar:",
                    ),
                ),
                (
                    "microcalcificaciones2",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            ("NI", "No identificada"),
                            ("PC", "Presente en CDIS"),
                            ("PN", "Presente en tejido no neoplásico"),
                            ("OT", "Otro (especificar)"),
                        ],
                        max_length=100,
                        verbose_name="Microcalcificaciones(todas las que apliquen)",
                    ),
                ),
                (
                    "otros_hallazgos_histologicos",
                    models.CharField(
                        blank=True,
                        max_length=5000,
                        null=True,
                        verbose_name="Otros hallazgos histológicos",
                    ),
                ),
                (
                    "otros_estudios_ihq",
                    models.CharField(
                        blank=True,
                        max_length=5000,
                        null=True,
                        verbose_name="Otros estudios: IHQ",
                    ),
                ),
                (
                    "comentarios",
                    models.CharField(
                        blank=True,
                        max_length=5000,
                        null=True,
                        verbose_name="Comentarios",
                    ),
                ),
                (
                    "diagnosticado_por",
                    models.CharField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="Diagnosticado por",
                    ),
                ),
                ("reated_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "biopsy",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="biopsy_diagnostic_mama_cdis",
                        to="pathologic_anathomy.biopsyrequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Diagnostico Biopcia de Mama(CDIS)",
                "verbose_name_plural": "Diagnosticos Biopcias de Mama(CDIS)",
                "ordering": ["id"],
            },
        ),
    ]
