# Generated by Django 3.2.13 on 2022-06-20 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Drug",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "drug_type",
                    models.IntegerField(
                        choices=[
                            (0, "Citostático"),
                            (1, "Inmuno Modulador"),
                            (2, "Anticuerpo Monoclonal"),
                            (3, "Concomitante"),
                            (4, "Bifosfonato"),
                            (5, "Vacuna Terapeutica"),
                        ],
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "presentation",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (0, "Bulbo"),
                            (1, "Ámpula"),
                            (2, "Frasco"),
                            (3, "Comprimido"),
                            (4, "Píldora"),
                            (5, "Pastilla"),
                        ],
                        null=True,
                        verbose_name="Presentación",
                    ),
                ),
                ("amount", models.FloatField(verbose_name="Cantidad")),
                (
                    "unit",
                    models.IntegerField(
                        blank=True,
                        choices=[(0, "g"), (1, "mg"), (2, "ml")],
                        null=True,
                        verbose_name="Unidad",
                    ),
                ),
                ("out_of_stock", models.BooleanField()),
            ],
            options={
                "verbose_name": "Fármaco de quimioterapia",
                "verbose_name_plural": "Fármacos de quimioterapia",
                "ordering": ["pk"],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="NuclearMedicineDrug",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
            ],
            options={
                "verbose_name": "Fármaco de medicina nuclear",
                "verbose_name_plural": "Fármacos de medicina nuclear",
                "ordering": ["pk"],
                "default_permissions": (),
            },
        ),
    ]
