# Generated by Django 3.2.13 on 2022-05-12 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Drug",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "type",
                    models.IntegerField(
                        choices=[(0, "Concomitante"), (1, "Citostático")],
                        verbose_name="Tipo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fármaco",
                "verbose_name_plural": "Fármacos",
            },
        ),
    ]
