# Generated by Django 3.2.13 on 2022-06-04 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("drugs", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="drug",
            old_name="type",
            new_name="drug_type",
        ),
    ]
