# Generated by Django 4.1.7 on 2023-03-31 03:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("drugs", "0002_alter_drug_out_of_stock"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="drug",
            options={
                "ordering": ["pk"],
                "verbose_name": "Fármaco de quimioterapia",
                "verbose_name_plural": "Fármacos de quimioterapia",
            },
        ),
        migrations.AlterModelOptions(
            name="nuclearmedicinedrug",
            options={
                "ordering": ["pk"],
                "verbose_name": "Fármaco de medicina nuclear",
                "verbose_name_plural": "Fármacos de medicina nuclear",
            },
        ),
    ]
