# Generated by Django 4.2.1 on 2023-06-08 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("patient", "0001_initial"),
        ("employee", "0001_initial"),
        ("drugs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("next_date", models.DateField(verbose_name="Fecha de próximo ciclo")),
            ],
            options={
                "verbose_name": "Ciclo",
                "verbose_name_plural": "Ciclos",
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="Scheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nombre")),
            ],
            options={
                "verbose_name": "Esquema",
                "verbose_name_plural": "Esquemas",
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="Protocol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "room",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "Quimioterapia"), (2, "Sala 1")],
                        null=True,
                        verbose_name="Lugar",
                    ),
                ),
                ("height", models.IntegerField(verbose_name="Talla")),
                ("weight", models.FloatField(verbose_name="Peso")),
                ("cycles", models.IntegerField(verbose_name="Cantidad de ciclos")),
                (
                    "stage",
                    models.IntegerField(
                        choices=[
                            (0, "In Situ"),
                            (1, "I"),
                            (2, "Ia"),
                            (3, "Ib"),
                            (4, "Ic"),
                            (5, "II"),
                            (6, "IIa"),
                            (7, "IIb"),
                            (8, "IIc"),
                            (9, "III"),
                            (10, "IIIa"),
                            (11, "IIIb"),
                            (12, "IIIc"),
                            (13, "IV"),
                            (14, "IVa"),
                            (15, "IVb"),
                            (16, "IVc"),
                            (17, "Desconocido"),
                            (18, "No Aplicable"),
                        ],
                        verbose_name="Etapa",
                    ),
                ),
                ("suspended", models.BooleanField()),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employee.doctor",
                        verbose_name="Doctor",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patient.patient",
                        verbose_name="Paciente",
                    ),
                ),
                (
                    "scheme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chemotherapy.scheme",
                        verbose_name="Esquema",
                    ),
                ),
            ],
            options={
                "verbose_name": "Protocolo",
                "verbose_name_plural": "Protocolos",
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="Medication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("days", models.IntegerField(verbose_name="Días")),
                (
                    "route",
                    models.IntegerField(
                        choices=[
                            (0, "Intramuscular"),
                            (1, "Intravenosa"),
                            (2, "Subcutaneo"),
                            (3, "Intradérmica"),
                            (4, "Oral"),
                        ],
                        verbose_name="Via de administración",
                    ),
                ),
                ("prescribed_dose", models.FloatField(verbose_name="Dosis prescrita")),
                (
                    "unit",
                    models.IntegerField(
                        blank=True,
                        choices=[(0, "g"), (1, "mg"), (2, "ml")],
                        null=True,
                        verbose_name="Unidad",
                    ),
                ),
                ("suspended", models.BooleanField(verbose_name="Suspendido")),
                (
                    "cause",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Causa"
                    ),
                ),
                (
                    "drug",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="drugs.drug",
                        verbose_name="Medicamento",
                    ),
                ),
                (
                    "protocol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chemotherapy.protocol",
                        verbose_name="Protocolo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Medicación",
                "verbose_name_plural": "Medicaciones",
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="CycleMedication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dose", models.FloatField(verbose_name="Dosis")),
                (
                    "unit",
                    models.IntegerField(
                        blank=True,
                        choices=[(0, "g"), (1, "mg"), (2, "ml")],
                        null=True,
                        verbose_name="Unidad",
                    ),
                ),
                (
                    "cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chemotherapy.cycle",
                        verbose_name="Ciclo",
                    ),
                ),
                (
                    "drug",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="drugs.drug",
                        verbose_name="Fármaco",
                    ),
                ),
            ],
            options={
                "verbose_name": "Medicación del ciclo",
                "verbose_name_plural": "Medicaciones del ciclo",
                "ordering": ["pk"],
            },
        ),
        migrations.AddField(
            model_name="cycle",
            name="protocol",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="chemotherapy.protocol",
                verbose_name="Protocolo",
            ),
        ),
    ]
