# Generated by Django 3.2.13 on 2022-06-20 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patient", "0005_alter_patient_options"),
        ("employee", "0003_auto_20220612_0006"),
    ]

    operations = [
        migrations.CreateModel(
            name="Scheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nombre")),
            ],
            options={
                "verbose_name": "Esquema",
                "verbose_name_plural": "Esquemas",
                "ordering": ["pk"],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="Protocol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "room",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "Quimioterapia"), (2, "Sala 1")],
                        null=True,
                        verbose_name="Lugar",
                    ),
                ),
                ("height", models.FloatField(verbose_name="Talla")),
                ("weight", models.FloatField(verbose_name="Peso")),
                ("cycles", models.IntegerField(verbose_name="Cantidad de ciclos")),
                (
                    "stage",
                    models.IntegerField(
                        choices=[
                            (0, "In Situ"),
                            (1, "I"),
                            (2, "Ia"),
                            (3, "Ib"),
                            (4, "Ic"),
                            (5, "II"),
                            (6, "IIa"),
                            (7, "IIb"),
                            (8, "IIc"),
                            (9, "III"),
                            (10, "IIIa"),
                            (11, "IIIb"),
                            (12, "IIIc"),
                            (13, "IV"),
                            (14, "IVa"),
                            (15, "IVb"),
                            (16, "IVc"),
                            (17, "Desconocido"),
                            (18, "No Aplicable"),
                        ],
                        verbose_name="Etapa",
                    ),
                ),
                ("suspended", models.BooleanField()),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employee.doctor",
                        verbose_name="Doctor",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patient.patient",
                        verbose_name="Paciente",
                    ),
                ),
                (
                    "scheme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chemotherapy.scheme",
                        verbose_name="Esquema",
                    ),
                ),
            ],
            options={
                "verbose_name": "Protocolo",
                "verbose_name_plural": "Protocolos",
                "ordering": ["pk"],
                "default_permissions": (),
            },
        ),
    ]
