# Generated by Django 3.2.13 on 2022-06-23 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drugs", "0002_alter_drug_out_of_stock"),
        ("chemotherapy", "0002_medication"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("next_date", models.DateField(verbose_name="Fecha de próximo ciclo")),
                (
                    "protocol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chemotherapy.protocol",
                        verbose_name="Protocolo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ciclo",
                "verbose_name_plural": "Ciclos",
                "ordering": ["pk"],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="CycleMedication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dose", models.FloatField(verbose_name="Dosis")),
                (
                    "unit",
                    models.IntegerField(
                        blank=True,
                        choices=[(0, "g"), (1, "mg"), (2, "ml")],
                        null=True,
                        verbose_name="Unidad",
                    ),
                ),
                (
                    "cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chemotherapy.cycle",
                        verbose_name="Ciclo",
                    ),
                ),
                (
                    "drug",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="drugs.drug",
                        verbose_name="Fármaco",
                    ),
                ),
            ],
            options={
                "verbose_name": "Medicación del ciclo",
                "verbose_name_plural": "Medicaciones del ciclo",
                "ordering": ["pk"],
                "default_permissions": (),
            },
        ),
    ]
