# Generated by Django 4.1.7 on 2023-03-31 03:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chemotherapy", "0003_cycle_cyclemedication"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cycle",
            options={
                "ordering": ["pk"],
                "verbose_name": "Ciclo",
                "verbose_name_plural": "Ciclos",
            },
        ),
        migrations.AlterModelOptions(
            name="cyclemedication",
            options={
                "ordering": ["pk"],
                "verbose_name": "Medicación del ciclo",
                "verbose_name_plural": "Medicaciones del ciclo",
            },
        ),
        migrations.AlterModelOptions(
            name="medication",
            options={
                "ordering": ["pk"],
                "verbose_name": "Medicación",
                "verbose_name_plural": "Medicaciones",
            },
        ),
        migrations.AlterModelOptions(
            name="protocol",
            options={
                "ordering": ["pk"],
                "verbose_name": "Protocolo",
                "verbose_name_plural": "Protocolos",
            },
        ),
        migrations.AlterModelOptions(
            name="scheme",
            options={
                "ordering": ["pk"],
                "verbose_name": "Esquema",
                "verbose_name_plural": "Esquemas",
            },
        ),
    ]
