# Generated by Django 4.2.1 on 2023-06-08 17:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("radiotherapy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="riskorgans",
            name="alpha_beta",
            field=models.IntegerField(default=0, verbose_name="Alpha/Beta"),
        ),
    ]
