# Generated by Django 4.2.1 on 2023-06-12 04:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("radiotherapy", "0002_riskorgans_alpha_beta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessories",
            name="eid",
            field=models.CharField(max_length=256, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="dosimetryplan",
            name="team",
            field=models.CharField(max_length=256, verbose_name="Equipo"),
        ),
        migrations.AlterField(
            model_name="energy",
            name="energy",
            field=models.CharField(max_length=256, verbose_name="Energía"),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="name",
            field=models.CharField(max_length=256, verbose_name="Nombre del equipo"),
        ),
        migrations.AlterField(
            model_name="medicalturn",
            name="address",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Dirección"
            ),
        ),
        migrations.AlterField(
            model_name="medicalturn",
            name="id",
            field=models.CharField(max_length=256, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="medicalturn",
            name="location",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Localización"
            ),
        ),
        migrations.AlterField(
            model_name="medicalturn",
            name="stage",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Etapa"
            ),
        ),
        migrations.AlterField(
            model_name="prescription",
            name="location",
            field=models.CharField(max_length=256, verbose_name="Localizacion"),
        ),
        migrations.AlterField(
            model_name="prescription",
            name="status",
            field=models.CharField(max_length=256, verbose_name="Estado"),
        ),
        migrations.AlterField(
            model_name="prescription",
            name="treatment_serie",
            field=models.CharField(max_length=256, verbose_name="Serie de Tratamiento"),
        ),
        migrations.AlterField(
            model_name="riskorgans",
            name="name",
            field=models.CharField(max_length=256, verbose_name="Nombre del Órgano"),
        ),
        migrations.AlterField(
            model_name="tacstudy",
            name="location",
            field=models.CharField(max_length=256, verbose_name="Localización"),
        ),
        migrations.AlterField(
            model_name="tacstudy",
            name="patient_position",
            field=models.CharField(
                max_length=256, verbose_name="Posición del Paciente"
            ),
        ),
        migrations.AlterField(
            model_name="tacstudy",
            name="protocol",
            field=models.CharField(max_length=256, verbose_name="Protocolo utilizado"),
        ),
    ]
