# Generated by Django 3.2.13 on 2022-04-27 02:46

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0003_patient_gender_view"),
        ("nuclear_medicine", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientHormonalStudy",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sample_number", models.AutoField(primary_key=True, serialize=False)),
                (
                    "tests",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            ("TSH", "TSH"),
                            ("T3", "T3"),
                            ("T4", "T4"),
                            ("T3F", "T3F"),
                            ("T4F", "T4F"),
                            ("PRL", "PRL"),
                            ("FSH", "FSH"),
                            ("LH", "LH"),
                            ("PRG", "PRG"),
                            ("E2", "E2"),
                            ("CORT", "CORT"),
                            ("INS", "INS"),
                            ("TEST", "TEST"),
                            ("GH", "GH"),
                        ],
                        max_length=250,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patient.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Estudio hormonal RIA-IRMA",
                "verbose_name_plural": "Estudios hormonales RIA-IRMA",
                "ordering": ["created_at"],
            },
        ),
    ]
