# Generated by Django 3.2.13 on 2022-06-12 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nuclear_medicine", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gammagraphy",
            options={
                "default_permissions": (),
                "ordering": ["pk"],
                "verbose_name": "Gammagrafía",
                "verbose_name_plural": "Gammagrafías",
            },
        ),
        migrations.AlterModelOptions(
            name="hormonalresult",
            options={
                "default_permissions": (),
                "ordering": ["pk"],
                "verbose_name": "Resultado hormonal RIA-IRMA",
                "verbose_name_plural": "Resultados hormonales RIA-IRMA",
            },
        ),
        migrations.AlterModelOptions(
            name="hormonalstudy",
            options={
                "default_permissions": (),
                "ordering": ["created_at"],
                "verbose_name": "Estudio hormonal RIA-IRMA",
                "verbose_name_plural": "Estudios hormonales RIA-IRMA",
            },
        ),
        migrations.AlterModelOptions(
            name="iodinedetection",
            options={
                "default_permissions": (),
                "ordering": ["pk"],
                "verbose_name": "Detección de yodo",
                "verbose_name_plural": "Detección de yodo",
            },
        ),
        migrations.AlterModelOptions(
            name="oncologicresult",
            options={
                "default_permissions": (),
                "ordering": ["pk"],
                "verbose_name": "Resultado oncología RIA-IRMA",
                "verbose_name_plural": "Resultados oncología RIA-IRMA",
            },
        ),
        migrations.AlterModelOptions(
            name="oncologicstudy",
            options={
                "default_permissions": (),
                "ordering": ["created_at"],
                "verbose_name": "Estudio oncológico RIA-IRMA",
                "verbose_name_plural": "Estudios oncológicos RIA-IRMA",
            },
        ),
        migrations.AlterModelOptions(
            name="serialiodinedetection",
            options={
                "default_permissions": (),
                "ordering": ["pk"],
                "verbose_name": "Detección de yodo seriada",
                "verbose_name_plural": "Detección de yodo seriada",
            },
        ),
    ]
