# Generated by Django 3.2.13 on 2022-05-12 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drugs", "0001_initial"),
        ("patient", "0003_patient_gender_view"),
        ("nuclear_medicine", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RadioIsotope",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
            ],
            options={
                "verbose_name": "Radio isótopo",
                "verbose_name_plural": "Radio isótopo",
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="Study",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
            ],
            options={
                "verbose_name": "Estudio",
                "verbose_name_plural": "Estudios",
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="Gammagraphy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("dose", models.FloatField()),
                ("report", models.TextField(max_length=5000)),
                ("observation", models.TextField(max_length=5000)),
                (
                    "drug",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="drugs.drug"
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patient.patient",
                    ),
                ),
                (
                    "radio_isotope",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nuclear_medicine.radioisotope",
                    ),
                ),
                (
                    "requested_study",
                    models.ManyToManyField(to="nuclear_medicine.Study"),
                ),
            ],
            options={
                "verbose_name": "Gammagrafía",
                "verbose_name_plural": "Gammagrafias",
                "ordering": ["pk"],
            },
        ),
    ]
