# Generated by Django 3.2.13 on 2022-05-03 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nuclear_medicine", "0002_patienthormonalstudy"),
    ]

    operations = [
        migrations.CreateModel(
            name="OncologicResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tsh", models.FloatField(blank=True, null=True)),
                ("t3", models.FloatField(blank=True, null=True)),
                ("t4", models.FloatField(blank=True, null=True)),
                ("tg", models.FloatField(blank=True, null=True)),
                ("anti_tg", models.FloatField(blank=True, null=True)),
                ("anti_tipo", models.FloatField(blank=True, null=True)),
                ("calcit", models.FloatField(blank=True, null=True)),
                ("ca19_9", models.FloatField(blank=True, null=True)),
                ("ca15_3", models.FloatField(blank=True, null=True)),
                ("ca125", models.FloatField(blank=True, null=True)),
                ("cea", models.FloatField(blank=True, null=True)),
                ("alf", models.FloatField(blank=True, null=True)),
                ("psa", models.FloatField(blank=True, null=True)),
                ("psafree", models.FloatField(blank=True, null=True)),
                (
                    "oncologic_study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nuclear_medicine.OncologicStudy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resultado oncología RIA-IRMA",
                "verbose_name_plural": "Resultados oncología RIA-IRMA",
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="HormonalResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tsh", models.FloatField(blank=True, null=True)),
                ("t3", models.FloatField(blank=True, null=True)),
                ("t4", models.FloatField(blank=True, null=True)),
                ("t3f", models.FloatField(blank=True, null=True)),
                ("t4f", models.FloatField(blank=True, null=True)),
                ("prl", models.FloatField(blank=True, null=True)),
                ("fsh", models.FloatField(blank=True, null=True)),
                ("lh", models.FloatField(blank=True, null=True)),
                ("prg", models.FloatField(blank=True, null=True)),
                ("e2", models.FloatField(blank=True, null=True)),
                ("cort", models.FloatField(blank=True, null=True)),
                ("ins", models.FloatField(blank=True, null=True)),
                ("test", models.FloatField(blank=True, null=True)),
                ("gh", models.FloatField(blank=True, null=True)),
                (
                    "hormonal_study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nuclear_medicine.patienthormonalstudy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resultado hormonal RIA-IRMA",
                "verbose_name_plural": "Resultados hormonales RIA-IRMA",
                "ordering": ["pk"],
            },
        ),
    ]
