# Generated by Django 4.1.7 on 2023-03-31 03:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("nuclear_medicine", "0002_auto_20220612_0006"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gammagraphy",
            options={
                "ordering": ["pk"],
                "verbose_name": "Gammagrafía",
                "verbose_name_plural": "Gammagrafías",
            },
        ),
        migrations.AlterModelOptions(
            name="hormonalresult",
            options={
                "ordering": ["pk"],
                "verbose_name": "Resultado hormonal RIA-IRMA",
                "verbose_name_plural": "Resultados hormonales RIA-IRMA",
            },
        ),
        migrations.AlterModelOptions(
            name="hormonalstudy",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Estudio hormonal RIA-IRMA",
                "verbose_name_plural": "Estudios hormonales RIA-IRMA",
            },
        ),
        migrations.AlterModelOptions(
            name="iodinedetection",
            options={
                "ordering": ["pk"],
                "verbose_name": "Detección de yodo",
                "verbose_name_plural": "Detección de yodo",
            },
        ),
        migrations.AlterModelOptions(
            name="oncologicresult",
            options={
                "ordering": ["pk"],
                "verbose_name": "Resultado oncología RIA-IRMA",
                "verbose_name_plural": "Resultados oncología RIA-IRMA",
            },
        ),
        migrations.AlterModelOptions(
            name="oncologicstudy",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Estudio oncológico RIA-IRMA",
                "verbose_name_plural": "Estudios oncológicos RIA-IRMA",
            },
        ),
        migrations.AlterModelOptions(
            name="serialiodinedetection",
            options={
                "ordering": ["pk"],
                "verbose_name": "Detección de yodo seriada",
                "verbose_name_plural": "Detección de yodo seriada",
            },
        ),
    ]
