# Generated by Django 3.2.13 on 2022-05-10 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0003_patient_gender_view"),
        ("nuclear_medicine", "0004_auto_20220504_0031"),
    ]

    operations = [
        migrations.CreateModel(
            name="SerialIodineDetection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("two_hours", models.FloatField()),
                ("four_hours", models.FloatField()),
                ("eight_hours", models.FloatField()),
                ("twenty_four_hours", models.FloatField()),
                ("forty_eight_hours", models.FloatField()),
                ("seventy_two_hours", models.FloatField()),
                ("ninety_six_hours", models.FloatField()),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patient.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detección de yodo",
                "verbose_name_plural": "Detección de yodo",
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="IodineDetection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("two_hours", models.FloatField()),
                ("twenty_four_hours", models.FloatField()),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patient.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detección de yodo",
                "verbose_name_plural": "Detección de yodo",
                "ordering": ["pk"],
            },
        ),
    ]
