# Generated by Django 3.2.13 on 2022-05-10 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nuclear_medicine", "0005_iodinedetection_serialiodinedetection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="iodinedetection",
            name="twenty_four_hours",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="iodinedetection",
            name="two_hours",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="serialiodinedetection",
            name="eight_hours",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="serialiodinedetection",
            name="forty_eight_hours",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="serialiodinedetection",
            name="four_hours",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="serialiodinedetection",
            name="ninety_six_hours",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="serialiodinedetection",
            name="twenty_four_hours",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="serialiodinedetection",
            name="two_hours",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
