# Generated by Django 3.2.13 on 2022-05-16 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nuclear_medicine", "0007_alter_serialiodinedetection_seventy_two_hours"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="serialiodinedetection",
            options={
                "ordering": ["pk"],
                "verbose_name": "Detección de yodo seriada",
                "verbose_name_plural": "Detección de yodo seriada",
            },
        ),
    ]
