# Generated by Django 3.2.13 on 2022-04-23 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0003_patient_gender_view"),
        ("cancer_registry", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TNM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tumor",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("TXTX", "Tx"),
                            ("T0", "T0"),
                            ("Tis", "Tis"),
                            ("T1", "T1"),
                            ("T2", "T2"),
                            ("T3", "T3"),
                            ("T4", "T4"),
                        ],
                        max_length=10,
                        verbose_name="Tumor",
                    ),
                ),
                (
                    "nodule",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NX", "NX"),
                            ("N0", "N0"),
                            ("N1", "N1"),
                            ("N2", "N2"),
                            ("N3", "N3"),
                        ],
                        max_length=10,
                        verbose_name="Nódulo",
                    ),
                ),
                (
                    "metastasis",
                    models.CharField(
                        blank=True,
                        choices=[("MX", "MX"), ("M0", "M0"), ("M1", "M1")],
                        max_length=10,
                        verbose_name="Metástasis",
                    ),
                ),
                (
                    "is_clinical",
                    models.BooleanField(
                        blank=True, default=False, verbose_name="Clínico"
                    ),
                ),
                (
                    "is_pathological",
                    models.BooleanField(
                        blank=True, default=False, verbose_name="Patológico"
                    ),
                ),
                (
                    "is_recurrent",
                    models.BooleanField(
                        blank=True, default=False, verbose_name="Recurrente"
                    ),
                ),
                (
                    "is_posttreatment",
                    models.BooleanField(
                        blank=True, default=False, verbose_name="Post-tratamiento"
                    ),
                ),
                (
                    "is_autopsy",
                    models.BooleanField(
                        blank=True, default=False, verbose_name="Autopsia"
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patient.patient",
                        verbose_name="Paciente",
                    ),
                ),
            ],
            options={
                "verbose_name": "TNM",
                "verbose_name_plural": "TNMs",
                "ordering": ["pk"],
            },
        ),
    ]
