# Generated by Django 3.2.13 on 2022-06-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cancer_registry", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="neoplasm",
            name="age_at_diagnosis",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Edad al momento de diagnóstico"
            ),
        ),
        migrations.AddField(
            model_name="neoplasm",
            name="psa",
            field=models.FloatField(blank=True, null=True, verbose_name="PSA"),
        ),
    ]
