# Generated by Django 3.2.13 on 2022-06-12 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cancer_registry", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="neoplasm",
            options={
                "default_permissions": (),
                "ordering": ["pk"],
                "verbose_name": "Neoplasia",
                "verbose_name_plural": "Neoplasias",
            },
        ),
    ]
