# Generated by Django 3.2.13 on 2022-04-25 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cancer_registry", "0002_tnm"),
    ]

    operations = [
        migrations.AddField(
            model_name="neoplasm",
            name="treatment_performed",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Cirugía"),
                    (2, "Quimioterapia"),
                    (3, "Radioterapia"),
                    (4, "Hormonoterapia"),
                    (0, "Ninguno"),
                ],
                null=True,
                verbose_name="Tratamiento realizado",
            ),
        ),
    ]
