# Generated by Django 4.1.7 on 2023-03-31 03:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cancer_registry", "0002_alter_neoplasm_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="neoplasm",
            options={
                "ordering": ["pk"],
                "verbose_name": "Neoplasia",
                "verbose_name_plural": "Neoplasias",
            },
        ),
    ]
