# Generated by Django 3.2.12 on 2022-04-14 17:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="identity_card",
            field=models.CharField(
                max_length=11,
                validators=[django.core.validators.MinLengthValidator(11)],
                verbose_name="Carnet de Identidad",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="race",
            field=models.IntegerField(
                choices=[
                    (0, "No Definido"),
                    (1, "Blanca"),
                    (2, "Negra"),
                    (3, "Mestizo"),
                    (4, "Amarillo"),
                ],
                default=0,
                verbose_name="Raza",
            ),
        ),
    ]
