# Generated by Django 3.2.13 on 2022-06-08 22:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patient", "0002_patient_gender_view"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="sex",
            field=models.IntegerField(
                blank=True,
                choices=[(0, "No definido"), (1, "Masculino"), (2, "Femenino")],
                null=True,
                verbose_name="Sexo",
            ),
        ),
    ]
