# Generated by Django 3.2.13 on 2022-06-04 19:17

from django.db import migrations, models

import apps.patient.validators


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0002_patient_gender_view"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="patient",
            name="patient_medical_record_identity_card_constraints",
        ),
        migrations.AlterField(
            model_name="patient",
            name="identity_card",
            field=models.CharField(
                max_length=11,
                validators=[
                    apps.patient.validators.IdentityCardValidator(6, 11),
                    apps.patient.validators.only_numbers_validator,
                ],
                verbose_name="Carnet de Identidad",
            ),
        ),
        migrations.AddConstraint(
            model_name="patient",
            constraint=models.UniqueConstraint(
                fields=("identity_card",), name="patient_identity_card_constraints"
            ),
        ),
    ]
