# Generated by Django 3.2.13 on 2022-06-07 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0003_auto_20220604_1917"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="address",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="age_at_diagnosis",
        ),
        migrations.AddField(
            model_name="patient",
            name="apartment",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Apartamento"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="between_streets",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Entre calles"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="building",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Edificio"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="division",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Reparto"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="number",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Número"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="street",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Calle"
            ),
        ),
    ]
