# Generated by Django 3.2.13 on 2022-06-11 22:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patient", "0003_alter_patient_sex"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="medical_record",
            field=models.CharField(
                blank=True,
                max_length=32,
                null=True,
                verbose_name="No. Historia Clínica",
            ),
        ),
    ]
