# Generated by Django 3.2.13 on 2022-06-07 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0004_auto_20220607_0402"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="date_of_birth",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de nacimiento"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="sex",
            field=models.IntegerField(
                blank=True,
                choices=[(0, "No definido"), (1, "Masculino"), (2, "Femenino")],
                null=True,
                verbose_name="Sexo",
            ),
        ),
    ]
