# Generated by Django 3.2.13 on 2022-06-12 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0004_alter_patient_medical_record"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="patient",
            options={
                "default_permissions": (),
                "ordering": ["updated_at"],
                "verbose_name": "Paciente",
                "verbose_name_plural": "pacientes",
            },
        ),
    ]
