# Generated by Django 4.1.7 on 2023-03-31 03:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("patient", "0005_alter_patient_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="patient",
            options={
                "ordering": ["updated_at"],
                "verbose_name": "Paciente",
                "verbose_name_plural": "pacientes",
            },
        ),
    ]
