# Generated by Django 4.1.7 on 2023-03-31 04:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("patient", "0006_alter_patient_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="patient",
            options={
                "ordering": ["updated_at"],
                "permissions": (
                    ("add_oncologic", "Puede añadir pacientes al registro de cáncer"),
                    ("view_oncologic", "Puede añadir pacientes al registro de cáncer"),
                    (
                        "change_oncologic",
                        "Puede añadir pacientes al registro de cáncer",
                    ),
                    (
                        "delete_oncologic",
                        "Puede añadir pacientes al registro de cáncer",
                    ),
                ),
                "verbose_name": "Paciente",
                "verbose_name_plural": "pacientes",
            },
        ),
    ]
