# Generated by Django 3.2.16 on 2023-02-27 12:21

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("patient", "0005_alter_patient_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pathology",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "authopsy_number",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Número de Autopsia",
                    ),
                ),
                (
                    "entry_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de ingreso"
                    ),
                ),
                (
                    "exit_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de egreso"
                    ),
                ),
                (
                    "eval_speciality",
                    models.TextField(
                        blank=True, null=True, verbose_name="Egreso (Especialidad)"
                    ),
                ),
                (
                    "eviseration_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de eviseración"
                    ),
                ),
                (
                    "eviseration_by",
                    models.TextField(
                        blank=True, null=True, verbose_name="Por (Eviseración)"
                    ),
                ),
                (
                    "disection_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de disección"
                    ),
                ),
                (
                    "disection_by",
                    models.TextField(
                        blank=True, null=True, verbose_name="Por (Disección)"
                    ),
                ),
                (
                    "dignostic_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de diagnóstico"
                    ),
                ),
                (
                    "diagnostic_by",
                    models.TextField(
                        blank=True, null=True, verbose_name="Por (Diagnóstico)"
                    ),
                ),
                (
                    "study_full",
                    models.TextField(
                        blank=True, null=True, verbose_name="Estudio Completo"
                    ),
                ),
                (
                    "study_micro",
                    models.TextField(
                        blank=True, null=True, verbose_name="Estudio Micro"
                    ),
                ),
                (
                    "hc_resume",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Resumen de Historia Clínica",
                    ),
                ),
                (
                    "tests",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            (
                                "Infarto del Miocardio agudo",
                                "Infarto del Miocardio agudo",
                            ),
                            (
                                "Infarto del Miocardio antiguo",
                                "Infarto del Miocardio antiguo",
                            ),
                            ("Hipertensión Arterial", "Hipertensión Arterial"),
                            (
                                "Enfermedades cardiovasculares",
                                "Enfermedades cardiovasculares",
                            ),
                            ("E.C.V Hemorrágica", "E.C.V Hemorrágica"),
                            ("E.C.V Oclusiva", "E.C.V Oclusiva"),
                            ("Tumor Maligno", "Tumor Maligno"),
                            ("Tromboembolia Pulmonar", "Tromboembolia Pulmonar"),
                            ("Diabetes Mellitus", "Diabetes Mellitus"),
                            ("Cirrosis Hepática", "Cirrosis Hepática"),
                            ("Fallo Multiorgánico", "Fallo Multiorgánico"),
                            ("Infección", "Infección"),
                            ("Bronconeumonía", "Bronconeumonía"),
                            ("Tuberculosis", "Tuberculosis"),
                            ("Otras", "Otras"),
                            ("Muerte Materna", "Muerte Materna"),
                            ("Directa", "Directa"),
                            ("Indirecta", "Indirecta"),
                            (
                                "Accidental (No Obstetrica)",
                                "Accidental (No Obstetrica)",
                            ),
                            ("Tardía", "Tardía"),
                            ("Muerte por hecho violento", "Muerte por hecho violento"),
                            ("Suicidio", "Suicidio"),
                            ("Homicidio", "Homicidio"),
                            ("Accidente de Transito", "Accidente de Transito"),
                            ("Otros Accidentes", "Otros Accidentes"),
                            ("Tabaquismo", "Tabaquismo"),
                            ("Alcoholismo", "Alcoholismo"),
                            ("Transplante", "Transplante"),
                            (
                                "Insufuciencia Renal Cronica",
                                "Insufuciencia Renal Cronica",
                            ),
                            ("Obesidad", "Obesidad"),
                        ],
                        max_length=250,
                    ),
                ),
                (
                    "external_habit",
                    models.TextField(
                        blank=True, null=True, verbose_name="Hábito externo"
                    ),
                ),
                (
                    "internal_habit",
                    models.TextField(
                        blank=True, null=True, verbose_name="Hábito interno"
                    ),
                ),
                (
                    "cavities",
                    models.TextField(blank=True, null=True, verbose_name="Cavidades"),
                ),
                (
                    "nerv_sistem",
                    models.TextField(
                        blank=True, null=True, verbose_name="Sistema Nervioso"
                    ),
                ),
                (
                    "respiratory_aparatus",
                    models.TextField(
                        blank=True, null=True, verbose_name="Aparato Respiratorio"
                    ),
                ),
                (
                    "cardiovascular_aparatus",
                    models.TextField(
                        blank=True, null=True, verbose_name="Aparato Cardiovascular"
                    ),
                ),
                (
                    "digestive_aparatus",
                    models.TextField(
                        blank=True, null=True, verbose_name="Aparato Disgestivo"
                    ),
                ),
                (
                    "urinal_aparatus",
                    models.TextField(
                        blank=True, null=True, verbose_name="Aparato Urinario"
                    ),
                ),
                (
                    "genital_aparatus",
                    models.TextField(
                        blank=True, null=True, verbose_name="Aparato Genital"
                    ),
                ),
                (
                    "hemollymphoietic_aparatus",
                    models.TextField(
                        blank=True, null=True, verbose_name="Aparato Hemolinfopoyético"
                    ),
                ),
                (
                    "endocrine_system",
                    models.TextField(
                        blank=True, null=True, verbose_name="Sistema Endocrino"
                    ),
                ),
                (
                    "osteo_mio_articular_system",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Sistema Osteo-Mio-Articular",
                    ),
                ),
                (
                    "brain_weight",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Peso del Cerebro"
                    ),
                ),
                (
                    "cerebellum_stream_w",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Peso Cerebelo y Tallo"
                    ),
                ),
                (
                    "right_lung_w",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Peso del Pulmón derecho"
                    ),
                ),
                (
                    "left_lung_w",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Peso del Pulmón izquierdo"
                    ),
                ),
                (
                    "heart_w",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Peso del Corazón"
                    ),
                ),
                (
                    "VI",
                    models.FloatField(blank=True, null=True, verbose_name="VI (mm)"),
                ),
                (
                    "VD",
                    models.FloatField(blank=True, null=True, verbose_name="VD (mm)"),
                ),
                (
                    "t_valve",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Válvula T (mm)"
                    ),
                ),
                (
                    "p_valve",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Válvula P (mm)"
                    ),
                ),
                ("M", models.FloatField(blank=True, null=True, verbose_name="M (mm)")),
                ("A", models.FloatField(blank=True, null=True, verbose_name="A (mm)")),
                (
                    "liver_w",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Peso del Hígado"
                    ),
                ),
                (
                    "r_kidney_w",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Peso del Riñón derecho"
                    ),
                ),
                (
                    "r_kidney_v",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Volumen del Riñón derecho"
                    ),
                ),
                (
                    "l_kidney_w",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Peso del Riñón izquierdo"
                    ),
                ),
                (
                    "l_kidney_v",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Volumen del Riñón izquierdo",
                    ),
                ),
                (
                    "pancreas_w",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Peso del Páncreas"
                    ),
                ),
                (
                    "spleen_w",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Peso del Bazo"
                    ),
                ),
                (
                    "thyroid",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Peso del Tiroides"
                    ),
                ),
                (
                    "macroscopic_conclusions",
                    models.TextField(
                        blank=True, null=True, verbose_name="Conclusiones Macroscópicas"
                    ),
                ),
                (
                    "CDM",
                    models.TextField(
                        blank=True, null=True, verbose_name="Diagnóstico Clínico CDM"
                    ),
                ),
                (
                    "CIM",
                    models.TextField(
                        blank=True, null=True, verbose_name="Diagnóstico Clínico CIM"
                    ),
                ),
                (
                    "CBM",
                    models.TextField(
                        blank=True, null=True, verbose_name="Diagnóstico Clínico CBM"
                    ),
                ),
                (
                    "CC",
                    models.TextField(
                        blank=True, null=True, verbose_name="Diagnóstico Clínico CC"
                    ),
                ),
                (
                    "other_anatopathologic_dignose",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Otros Diagnósticos Anatopatológicos",
                    ),
                ),
                (
                    "observation_epicrisis",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observaciones (Epicrisis)"
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patient.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Infrome de Autopsia",
                "verbose_name_plural": "Informes de Autopsia",
                "ordering": ["created_at"],
                "default_permissions": (),
            },
        ),
    ]
