# Generated by Django 3.2.16 on 2023-02-28 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathological_anatomy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathology',
            name='pathologist',
            field=models.TextField(blank=True, null=True, verbose_name='Patólogo'),
        ),
    ]
