# Generated by Django 4.1.7 on 2023-03-31 03:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0003_auto_20220612_0006"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="doctor",
            options={
                "ordering": ["personal_record_number"],
                "verbose_name": "Doctor",
                "verbose_name_plural": "Doctor",
            },
        ),
        migrations.AlterModelOptions(
            name="group",
            options={
                "ordering": ["pk"],
                "verbose_name": "Grupo",
                "verbose_name_plural": "Grupo",
            },
        ),
    ]
