# Generated by Django 4.2.1 on 2023-06-08 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("patient", "0001_initial"),
        ("geographic_location", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeathCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direct_death_cause",
                    models.TextField(verbose_name="Causa de Muerte"),
                ),
                ("indirect_death_cause_1", models.JSONField(blank=True, null=True)),
                ("indirect_death_cause_2", models.JSONField(blank=True, null=True)),
                ("indirect_death_cause_3", models.JSONField(blank=True, null=True)),
                (
                    "other_contributing_diseases",
                    models.JSONField(blank=True, null=True),
                ),
                (
                    "datetime_of_death",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha y hora de defunción"
                    ),
                ),
                (
                    "scholarship_level",
                    models.IntegerField(
                        choices=[
                            (0, "Ninguno"),
                            (1, "Primaria"),
                            (2, "Secundaria Básica"),
                            (3, "Obrero Calificado"),
                            (4, "Pre-Universitario"),
                            (5, "Técnico Medio"),
                            (6, "Universitario"),
                            (7, "Ignorado(a)"),
                        ],
                        default=7,
                        verbose_name="Nivel de Escolaridad",
                    ),
                ),
                (
                    "civil_state",
                    models.IntegerField(
                        choices=[
                            (1, "Casado(a)"),
                            (2, "Unido"),
                            (3, "Divorciado"),
                            (4, "Separado"),
                            (5, "Viudo"),
                            (6, "Soltero"),
                            (7, "Ignorado(a)"),
                        ],
                        default=7,
                        verbose_name="Estado Civil",
                    ),
                ),
                (
                    "residence_type",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "Permanente"),
                            (2, "Temporal"),
                            (3, "Ignorado(a)"),
                        ],
                        null=True,
                        verbose_name="Tipo de Residencia",
                    ),
                ),
                (
                    "death_place",
                    models.IntegerField(
                        choices=[
                            (1, "Cuerpo de Guardia Hospitalario"),
                            (2, "Ingreso Hospitalario"),
                            (3, "Policlínico"),
                            (4, "Otro Centro Hospitalario"),
                            (5, "Domicilio"),
                            (6, "Otro Lugar"),
                            (7, "Ignorado(a)"),
                        ],
                        default=7,
                        verbose_name="Sitio de Defunción",
                    ),
                ),
                (
                    "pregnancy",
                    models.IntegerField(
                        choices=[(1, "Sí"), (2, "No"), (3, "Ignorado(a)")],
                        default=3,
                        verbose_name="Embarazo en los últimos 12 meses",
                    ),
                ),
                (
                    "pregnancy_result",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "Aborto"),
                            (2, "Parto por Cesárea"),
                            (3, "Parto Pelviano"),
                            (4, "Murió estando embarazada"),
                            (5, "Ignorado(a)"),
                        ],
                        null=True,
                        verbose_name="Resultado del embarazo",
                    ),
                ),
                (
                    "date_of_pregnancy",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha del embarazo"
                    ),
                ),
                (
                    "confirmation_causes",
                    models.IntegerField(
                        choices=[
                            (1, "Clínica"),
                            (2, "Investigación"),
                            (3, "Operación"),
                            (4, "Biopsia"),
                            (5, "Necropsia"),
                            (6, "Reconocimiento"),
                        ],
                        default=1,
                        verbose_name="Confirmación de las causas",
                    ),
                ),
                (
                    "certification_made_by",
                    models.IntegerField(
                        choices=[
                            (1, "Guardia"),
                            (2, "Asistencia"),
                            (3, "Familia"),
                            (4, "Legista"),
                            (5, "Otro"),
                        ],
                        default=1,
                        verbose_name="Certificación realizada por médico de",
                    ),
                ),
                (
                    "last_surgeries",
                    models.IntegerField(
                        choices=[(1, "Sí"), (2, "No"), (3, "Ignorado(a)")],
                        default=3,
                        verbose_name="Cirugías en las últimas 4 semanas",
                    ),
                ),
                (
                    "surgery_reasons",
                    models.TextField(
                        blank=True, null=True, verbose_name="Razón de la Cirugía"
                    ),
                ),
                (
                    "violent_death_causes",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "Accidente"),
                            (2, "Suicidio"),
                            (3, "Homicidio"),
                            (4, "Otro"),
                            (5, "Por Investigar"),
                        ],
                        null=True,
                        verbose_name="Causa aparente de muerte violenta",
                    ),
                ),
                (
                    "date_of_injury",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de la lesión"
                    ),
                ),
                (
                    "place_where_injury_occurred",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Lugar donde ocurrió la lesión",
                    ),
                ),
                (
                    "event_description",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Descripción de como ocurrió",
                    ),
                ),
                (
                    "requesting_authority",
                    models.TextField(verbose_name="Autoridad que solicita"),
                ),
                ("act_number", models.TextField(verbose_name="Número de Acta")),
                (
                    "death_location",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="residence_location_death",
                        to="geographic_location.location",
                        verbose_name="Localidad de defunción",
                    ),
                ),
                (
                    "patient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patient.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Certificado de Defunción",
                "verbose_name_plural": "Certificados de Defunción",
                "ordering": ["pk"],
            },
        ),
    ]
