# Generated by Django 3.2.16 on 2023-02-07 15:45

import django.db.models.deletion
from django.db import migrations, models

import apps.patient.validators


class Migration(migrations.Migration):
    dependencies = [
        ("geographic_location", "0002_auto_20220612_0006"),
        ("death_certificate", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deathcertificate",
            name="born_municipality",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="born_municipality_death",
                to="geographic_location.municipality",
                verbose_name="Municipio natal",
            ),
        ),
        migrations.AddField(
            model_name="deathcertificate",
            name="identity_card",
            field=models.CharField(
                default=0,
                max_length=11,
                validators=[
                    apps.patient.validators.IdentityCardValidator(6, 11),
                    apps.patient.validators.only_numbers_validator,
                ],
                verbose_name="Carnet de Identidad",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="deathcertificate",
            name="race",
            field=models.IntegerField(
                choices=[
                    (0, "No Definido"),
                    (1, "Blanca"),
                    (2, "Negra"),
                    (3, "Mestizo"),
                    (4, "Amarillo"),
                ],
                default=0,
                verbose_name="Raza",
            ),
        ),
        migrations.AddField(
            model_name="deathcertificate",
            name="residence_municipality",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="residence_municipality_death",
                to="geographic_location.municipality",
                verbose_name="Municipio de residencia",
            ),
        ),
        migrations.AddField(
            model_name="deathcertificate",
            name="sex",
            field=models.IntegerField(
                blank=True,
                choices=[(0, "No definido"), (1, "Masculino"), (2, "Femenino")],
                null=True,
                verbose_name="Sexo",
            ),
        ),
    ]
