# Generated by Django 3.2.16 on 2023-02-08 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('death_certificate', '0003_deathcertificate_date_of_death'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deathcertificate',
            name='date_of_death',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Hora de defunción'),
        ),
    ]
