# Generated by Django 3.2.16 on 2023-02-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('death_certificate', '0004_alter_deathcertificate_date_of_death'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deathcertificate',
            name='date_of_death',
        ),
        migrations.AddField(
            model_name='deathcertificate',
            name='time_of_death',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de defunción'),
        ),
    ]
