# Generated by Django 3.2.16 on 2023-02-28 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pathological_anatomy', '0001_initial'),
        ('death_certificate', '0005_auto_20230215_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deathcertificate',
            name='id',
        ),
        migrations.AddField(
            model_name='deathcertificate',
            name='authopsy_number',
            field=models.OneToOneField(default=20, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pathological_anatomy.pathology'),
            preserve_default=False,
        ),
    ]
